### ISSUE TITLE
Crash when setEffectsVolume

### ISSUE THREAD

**Issue by honghui** [cocos2d/cocos2d-x#11716]
cocos2dx version: cocos2d-js 3.3
Product Version: 5.7.0.1410
Hardware: SM-N9002;Android 4.3,level 18

The crash stack is:
java.util.ConcurrentModificationException: empty message
java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
java.util.HashMap$EntryIterator.next(HashMap.java:843)
java.util.HashMap$EntryIterator.next(HashMap.java:841)
org.cocos2dx.lib.Cocos2dxSound.setEffectsVolume(Unknown Source)
org.cocos2dx.lib.Cocos2dxHelper.setEffectsVolume(Unknown Source)
org.cocos2dx.lib.Cocos2dxRenderer.nativeRender(Native Method)
org.cocos2dx.lib.Cocos2dxRenderer.onDrawFrame(Unknown Source)
android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

and I find the same problem on the forum:http://discuss.cocos2d-x.org/t/android-cocos2dxsound-has-concurrentmodificationexception/10461/5

**Comment by atinagrawal** [comment]
@minggo: Any comments on this issue? I'm receiving this crash hundreds of times daily from different users. Please provide a final solution as soon as possible.

Here is the log:

java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextEntry(HashMap.java:851)
	at java.util.HashMap$EntryIterator.next(HashMap.java:891)
	at java.util.HashMap$EntryIterator.next(HashMap.java:890)
	at org.cocos2dx.lib.Cocos2dxSound.setEffectsVolume(Cocos2dxSound.java:250)
	at org.cocos2dx.lib.Cocos2dxHelper.setEffectsVolume(Cocos2dxHelper.java:419)
	at org.cocos2dx.lib.Cocos2dxRenderer.nativeRender(Native Method)
	at org.cocos2dx.lib.Cocos2dxRenderer.onDrawFrame(Cocos2dxRenderer.java:104)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1553)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1253)

**Comment by minggo** [comment]
@atinagrawal it seems there is a solution in [this ticket](http://discuss.cocos2d-x.org/t/android-cocos2dxsound-has-concurrentmodificationexception/10461/7), you can have a try. Did you modify the volume in a new thread?

**Comment by minggo** [comment]
@atinagrawal any feedback is appreciated.

**Comment by minggo** [comment]
duplicated with https://github.com/cocos2d/cocos2d-x/issues/17474

**Comment by atinagrawal** [comment]
Thank you for the solution.
