### ISSUE TITLE
csb or json exported by CocosStudio 2.2.6 can not be loaded by cocos 3.6 

### ISSUE THREAD

**Issue by travnick** [cocos2d/cocos2d-x#11930]
After migrating from cocos 3.0 to 3.6 it appears that all gui is messed up. So I decide to import into CososStudio 2.2.6 files from CocosStudio 1.6. It works, it exports (as json or csb) but while trying to load those files then it crashes.
`json`:

```
//code to load json files:
auto layout = cocostudio::GUIReader::getInstance()->widgetFromJsonFile(fileName.c_str());

// console output
[...]cocos2d-x-3.6/external/json/document.h:620:
rapidjson::GenericValue<Encoding, Allocator>::Member* rapidjson::GenericValue<Encoding, Allocator>::FindMember(const Ch*) [with Encoding = rapidjson::UTF8<>;
Allocator = rapidjson::MemoryPoolAllocator<>;
rapidjson::GenericValue<Encoding, Allocator>::Ch = char]: Assertion `IsObject()' failed.
```

`csb`:

```
//code to load csb files:
auto layout = cocostudio::GUIReader::getInstance()->widgetFromBinaryFile(fileName.c_str());

//and layout is here nullptr ...
ASAN:SIGSEGV                                                                                                                                                                                                    
=================================================================                                                                                                                                               
==8338==ERROR: AddressSanitizer: SEGV on unknown address 0x621065677cb6 (pc 0x000000b2dbcc sp 0x7fff6c053fd0 bp 0x7fff6c054010 T0)                                                                              
    #0 0xb2dbcb in cocostudio::stExpCocoNode::GetType(cocostudio::CocoLoader*) [cocos_3.6_path]/cocos/editor-support/cocostudio/CocoLoader.cpp:45                                
    #1 0xb1f968 in cocostudio::GUIReader::widgetFromBinaryFile(char const*) [cocos_3.6_path]/cocos/editor-support/cocostudio/CCSGUIReader.cpp:382                                
    #2 0x8d1c1e in Layer::Layer(Config const&) [project_path]/Classes/view/Layer.cpp:17                                                                       
    #3 0x88468c in Scene::createLayers(Config const&) [project_path]/Classes/controller/Scene.cpp:41                                                          
    #4 0x817bca in controller::Application::getScene(std::string const&) [project_path]/Classes/controller/Application.cpp:190
    #5 0x8174cb in controller::Application::activateScene(std::string const&) [project_path]/Classes/controller/Application.cpp:147
    #6 0x81715b in controller::Application::applicationDidFinishLaunching() [project_path]/Classes/controller/Application.cpp:124
    #7 0xa34685 in cocos2d::Application::run() [cocos_3.6_path]/cocos/platform/linux/CCApplication-linux.cpp:68
    #8 0x8138f2 in main [project_path]/proj.linux/main.cpp:37
    #9 0x7fa6fb4167ff in __libc_start_main (/usr/lib/libc.so.6+0x207ff)
    #10 0x813608 in _start ([bin_path]/Game+0x813608)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV [cocos_3.6_path]/cocos/editor-support/cocostudio/CocoLoader.cpp:45 cocostudio::stExpCocoNode::GetType(cocostudio::CocoLoader*)
==8338==ABORTINGG
```

**Comment by travnick** [comment]
Any progress here? Do you need anything more? I'm really interested in quick fix/workaround for that issue.

**Comment by travnick** [comment]
I'm really interested in get the issue resolved. Is there any possibility to fix this or create a workaround?

**Comment by minggo** [comment]
Cocos Studio has been EOL'd as of April 2016.  There will be no more releases of Cocos Studio.

The last version of Cocos Studio is v3.10 and can be downloaded for [Mac](http://www.cocos2d-x.org/filedown/CocosForMac-v3.10.dmg) and [Windows](http://www.cocos2d-x.org/filedown/CocosForWin-v3.10.exe).
This version of Cocos Studio requires version [v3.10](http://www.cocos2d-x.org/filedown/cocos2d-x-3.10.zip) of Cocos2d-x.
This version of Cocos Studio works best in Windows 7 and OS X 10.10.

If you update Cocos2d-x to a version greater than v3.10, you may experience compatibility issues.
If you run Cocos Studio on Windows 10 or OS X 10.11, you may experience compatibility issues.
