### ISSUE TITLE
audio pauseAllEffects crash

### ISSUE THREAD

**Issue by huangwei1024** [cocos2d/cocos2d-x#11999]
``` java
java.util.ConcurrentModificationException
at java.util.HashMap$HashIterator.nextEntry(HashMap.java:806)
at java.util.HashMap$EntryIterator.next(HashMap.java:843)
at java.util.HashMap$EntryIterator.next(HashMap.java:841)
at org.cocos2dx.lib.Cocos2dxSound.pauseAllEffects(Cocos2dxSound.java:207)
at org.cocos2dx.lib.Cocos2dxHelper.pauseAllEffects(Cocos2dxHelper.java:240)
at org.cocos2dx.lib.Cocos2dxRenderer.nativeRender(Native Method)
at org.cocos2dx.lib.Cocos2dxRenderer.onDrawFrame(Cocos2dxRenderer.java:104)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1531)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)
```

看崩溃log应该是多线程操作audio里的hashmap导致的，不明白为啥没加锁保护，或者本来这就不可能有多线程访问的情况？

测试中多种机型均存在该问题，结果就是导致程序直接崩溃。。。

**Comment by huangwei1024** [comment]
这是其它线程状态

``` java
Thread-3170　(id=3170，state=RUNNABLE)
    dalvik.system.VMStack.getThreadStackTrace(Native Method)
    java.lang.Thread.getStackTrace(Thread.java:579)
    java.lang.Thread.getAllStackTraces(Thread.java:521)
    com.testin.agent.d.f.a(Unknown Source)
    com.testin.agent.d.a.a(Unknown Source)
    com.testin.agent.a.c.run(Unknown Source)
SoundPool　(id=3168，state=RUNNABLE)
    dalvik.system.NativeStart.run(Native Method)
Signal Catcher　(id=3032，state=WAITING)
    dalvik.system.NativeStart.run(Native Method)
Binder_3　(id=3048，state=RUNNABLE)
    dalvik.system.NativeStart.run(Native Method)
Binder_1　(id=3037，state=RUNNABLE)
    dalvik.system.NativeStart.run(Native Method)
ReferenceQueueDaemon　(id=3034，state=WAITING)
    java.lang.Object.wait(Native Method)
    java.lang.Object.wait(Object.java:364)
    java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:130)
    java.lang.Thread.run(Thread.java:841)
GC　(id=3031，state=RUNNABLE)
    dalvik.system.NativeStart.run(Native Method)
Compiler　(id=3033，state=WAITING)
    dalvik.system.NativeStart.run(Native Method)
Binder_2　(id=3038，state=RUNNABLE)
    dalvik.system.NativeStart.run(Native Method)
FinalizerWatchdogDaemon　(id=3036，state=WAITING)
    java.lang.Object.wait(Native Method)
    java.lang.Object.wait(Object.java:364)
    java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:230)
    java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:207)
    java.lang.Thread.run(Thread.java:841)
main　(id=1，state=RUNNABLE)
    android.os.MessageQueue.nativePollOnce(Native Method)
    android.os.MessageQueue.next(MessageQueue.java:138)
    android.os.Looper.loop(Looper.java:123)
    android.app.ActivityThread.main(ActivityThread.java:5356)
    java.lang.reflect.Method.invokeNative(Native Method)
    java.lang.reflect.Method.invoke(Method.java:515)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
    dalvik.system.NativeStart.main(Native Method)
FinalizerDaemon　(id=3035，state=WAITING)
    java.lang.Object.wait(Native Method)
    java.lang.Object.wait(Object.java:401)
    java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:102)
    java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:73)
    java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
    java.lang.Thread.run(Thread.java:841)
java.lang.ProcessManager　(id=3149，state=WAITING)
    java.lang.Object.wait(Native Method)
    java.lang.Object.wait(Object.java:364)
    java.lang.ProcessManager.waitForMoreChildren(ProcessManager.java:140)
    java.lang.ProcessManager.watchChildren(ProcessManager.java:105)
    java.lang.ProcessManager.access$000(ProcessManager.java:40)
    java.lang.ProcessManager$1.run(ProcessManager.java:58)
SoundPoolThread　(id=3169，state=RUNNABLE)
    dalvik.system.NativeStart.run(Native Method)
pool-2-thread-1　(id=3047，state=WAITING)
    java.lang.Object.wait(Native Method)
    java.lang.Thread.parkFor(Thread.java:1205)
    sun.misc.Unsafe.park(Unsafe.java:325)
    java.util.concurrent.locks.LockSupport.park(LockSupport.java:157)
    java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2017)
    java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1050)
    java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:778)
    java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1035)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1097)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    java.lang.Thread.run(Thread.java:841)
Binder_4　(id=3061，state=RUNNABLE)
    dalvik.system.NativeStart.run(Native Method)
```

**Comment by walzer** [comment]
引擎版本？安卓版本？
`SimpleAudioEngine` 本身并不是设计为线程安全的。如果你需要在不同线程里面调用，则需要自己加上锁。

**Comment by pandamicro** [comment]
@huangwei1024 Do you have any further informations ? As walzer mentioned, SimpleAudioEngine doesn't support multi thread usage, and we don't know how to reproduce the issue.

I will close it for now, if you have any more informations and the steps to reproduce this issue, please comment, and I will reopen it.

Besides, we suggest new AudioEngine than SimpleAudioEngine (it doesn't support multi thread neither).

**Comment by ghost** [comment]
不是外部的多线程引起的，而是音频模块有多线程。

```java
public class OnLoadCompletedListener implements SoundPool.OnLoadCompleteListener {
```

这个回调函数在另外的线程中；

OnLoadCompletedListener
    -> doPlayEffect
        -> this.mPathStreamIDsMap.put(pPath, streamIDs); // 有两个线程同时访问 mPathStreamIDsMap 的情况

使用 `ConcurrentHashMap` 就好了；
