### ISSUE TITLE
Build for android error

### ISSUE THREAD

**Issue by purepure** [cocos2d/cocos2d-x#13068]
I finish my game on ios and run it very well, but when I try to build for android, it got so many error
I think it come from compiler. Please take a look and help
Thank

Here is the log:

<code>
Please use cocos console instead.

Running command: compile
Building mode: debug
Android platform not specified, searching a default one...
running: '/Volumes/Data/Dev/Android/android-sdk-macosx/tools/android update project -t android-17 -p /Volumes/Data/AndroidProj/ChickenRun_v4/proj.android'

Updated project.properties
Updated local.properties
Updated file /Volumes/Data/AndroidProj/ChickenRun_v4/proj.android/proguard-project.txt
It seems that there are sub-projects. If you want to update them
please use the --subprojects parameter.
Android platform not specified, searching a default one...
running: '/Volumes/Data/Dev/Android/android-sdk-macosx/tools/android update lib-project -p /Volumes/Data/AndroidProj/ChickenRun_v4/proj.android/../cocos2d/cocos/platform/android/java -t android-10'

Updated project.properties
Updated local.properties
Updated file /Volumes/Data/AndroidProj/ChickenRun_v4/proj.android/../cocos2d/cocos/platform/android/java/proguard-project.txt
Building native...
NDK build mode: debug
NDK_TOOLCHAIN_VERSION: 4.9
running: '/Volumes/Data/Dev/Android/ndk/android-ndk-r10e/ndk-build -C /Volumes/Data/AndroidProj/ChickenRun_v4/proj.android -j4 NDK_MODULE_PATH=/Volumes/Data/AndroidProj/ChickenRun_v4/proj.android/../cocos2d:/Volumes/Data/AndroidProj/ChickenRun_v4/proj.android/../cocos2d/cocos:/Volumes/Data/AndroidProj/ChickenRun_v4/proj.android/../cocos2d/external NDK_TOOLCHAIN_VERSION=4.9 NDK_DEBUG=1'

Android NDK: WARNING: APP_PLATFORM android-17 is larger than android:minSdkVersion 9 in ./AndroidManifest.xml  
make: Entering directory `/Volumes/Data/AndroidProj/ChickenRun_v4/proj.android'
/Volumes/Data/Dev/Android/ndk/android-ndk-r10e/build/core/build-binary.mk:466: warning: overriding commands for target`obj/local/armeabi/objs-debug/bullet_static/BulletMultiThreaded/SpuLibspe2Support.o'
/Volumes/Data/Dev/Android/ndk/android-ndk-r10e/build/core/build-binary.mk:466: warning: ignoring old commands for target `obj/local/armeabi/objs-debug/bullet_static/BulletMultiThreaded/SpuLibspe2Support.o'
Android NDK: WARNING: Unsupported source file extensions in jni/Android.mk for module cocos2dcpp_shared    
Android NDK:   ../../Classes/BaseViewController.h ../../Classes/CHybrid.mm    
/Volumes/Data/Dev/Android/ndk/android-ndk-r10e/build/core/build-binary.mk:466: warning: overriding commands for target`obj/local/armeabi-v7a/objs-debug/bullet_static/BulletMultiThreaded/SpuLibspe2Support.o'
/Volumes/Data/Dev/Android/ndk/android-ndk-r10e/build/core/build-binary.mk:466: warning: ignoring old commands for target `obj/local/armeabi-v7a/objs-debug/bullet_static/BulletMultiThreaded/SpuLibspe2Support.o'
Android NDK: WARNING: Unsupported source file extensions in jni/Android.mk for module cocos2dcpp_shared    
Android NDK:   ../../Classes/BaseViewController.h ../../Classes/CHybrid.mm    
/Volumes/Data/Dev/Android/ndk/android-ndk-r10e/build/core/build-binary.mk:466: warning: overriding commands for target`obj/local/x86/objs-debug/bullet_static/BulletMultiThreaded/SpuLibspe2Support.o'
/Volumes/Data/Dev/Android/ndk/android-ndk-r10e/build/core/build-binary.mk:466: warning: ignoring old commands for target `obj/local/x86/objs-debug/bullet_static/BulletMultiThreaded/SpuLibspe2Support.o'
Android NDK: WARNING: Unsupported source file extensions in jni/Android.mk for module cocos2dcpp_shared    
Android NDK:   ../../Classes/BaseViewController.h ../../Classes/CHybrid.mm    
[armeabi] Compile++ thumb: cocos2dcpp_shared <= Chicken.cpp
[armeabi] Compile++ thumb: cocos2dcpp_shared <= GameManager.cpp
[armeabi] Compile++ thumb: cocos2dcpp_shared <= GameScene.cpp
[armeabi] Compile++ thumb: cocos2dcpp_shared <= Help.cpp
In file included from jni/../../Classes/Chicken.h:14:0,
                 from jni/../../Classes/Chicken.cpp:9:
jni/../../Classes/Utils.h:19:17: error: 'cocos2d' is not a namespace-name
 using namespace cocos2d;
                 ^
jni/../../Classes/Utils.h:19:24: error: expected namespace-name before ';' token
 using namespace cocos2d;
                        ^
jni/../../Classes/Utils.h:23:12: error: 'Vector' does not name a type
     static Vector<SpriteFrame*> getSpriteFrames(const char *name, int from, int to);
            ^
jni/../../Classes/Utils.h:24:12: error: 'Animate' does not name a type
     static Animate* createAnimated(Vector<SpriteFrame*> frames, float speed);
            ^
jni/../../Classes/Utils.h:25:12: error: 'Animate' does not name a type
     static Animate* createAnimated(const char *name, int from, int to, float speed);
            ^
jni/../../Classes/Utils.h:29:27: error: 'Node' has not been declared
     static void drawPoint(Node *node, Vec2 position);
                           ^
jni/../../Classes/Utils.h:29:39: error: 'Vec2' has not been declared
     static void drawPoint(Node *node, Vec2 position);
                                       ^
jni/../../Classes/Utils.h:30:12: error: 'PhysicsBody' does not name a type
     static PhysicsBody* applyPhysicBody(Sprite *sprite, int type, int hitType);
            ^
jni/../../Classes/Utils.h:31:12: error: 'PhysicsBody' does not name a type
     static PhysicsBody* applyPhysicBody(Sprite *sprite, cocos2d::Size size, int type, int hitType);
            ^
jni/../../Classes/Utils.h:33:17: error: 'string' in namespace 'std' does not name a type
     static std::string formatTimer(int second);
                 ^
jni/../../Classes/Utils.h:35:23: error: 'Node' has not been declared
     static void pause(Node *node);
                       ^
jni/../../Classes/Utils.h:36:24: error: 'Node' has not been declared
     static void resume(Node *node);
                        ^
jni/../../Classes/Utils.h:37:35: error: 'Node' has not been declared
     static void removeAllChildren(Node *node);
                                   ^
jni/../../Classes/Utils.h:39:33: error: 'Node' has not been declared
     static void setGlobalZIndex(Node *node, int z);
                                 ^
jni/../../Classes/Utils.h:41:17: error: 'string' in namespace 'std' does not name a type
     static std::string readFile(std::string relativePath);
                 ^
jni/../../Classes/Utils.h:43:28: error: 'Node' has not been declared
     static void flashColor(Node *node, Color3B startColor, Color3B backColor, int blinkCount, float duration);
                            ^
jni/../../Classes/Utils.h:43:40: error: 'Color3B' has not been declared
     static void flashColor(Node *node, Color3B startColor, Color3B backColor, int blinkCount, float duration);
                                        ^
jni/../../Classes/Utils.h:43:60: error: 'Color3B' has not been declared
     static void flashColor(Node *node, Color3B startColor, Color3B backColor, int blinkCount, float duration);
                                                            ^
In file included from jni/../../Classes/Chicken.h:16:0,
                 from jni/../../Classes/Chicken.cpp:9:
jni/../../Classes/Lane.h:21:28: error: expected class-name before '{' token
 class LaneData : public Ref{
                            ^
jni/../../Classes/Lane.h:30:21: error: 'cocos2d' has not been declared
 class Lane : public cocos2d::Sprite{
                     ^
jni/../../Classes/Lane.h:30:30: error: expected '{' before 'Sprite'
 class Lane : public cocos2d::Sprite{
                              ^
jni/../../Classes/Lane.h:30:36: error: invalid type in declaration before '{' token
 class Lane : public cocos2d::Sprite{
                                    ^
jni/../../Classes/Lane.h:31:1: error: expected primary-expression before 'private'
 private:
 ^
jni/../../Classes/Lane.h:31:1: error: expected '}' before 'private'
jni/../../Classes/Lane.h:31:1: error: expected ',' or ';' before 'private'
jni/../../Classes/Lane.h:35:1: error: expected unqualified-id before 'public'
 public:
 ^
jni/../../Classes/Lane.h:43:10: error: expected unqualified-id before 'int'
     Lane(int type);
          ^
jni/../../Classes/Lane.h:43:10: error: expected ')' before 'int'
jni/../../Classes/Lane.h:44:10: error: expected unqualified-id before 'int'
     Lane(int type, int direction, int speed, float ratio);
          ^
jni/../../Classes/Lane.h:44:10: error: expected ')' before 'int'
jni/../../Classes/Lane.h:50:5: error: 'Vec2' does not name a type
     Vec2 getStartPoint();
     ^
jni/../../Classes/Lane.h:51:5: error: 'Vec2' does not name a type
     Vec2 getEndPoint();
     ^
jni/../../Classes/Lane.h:52:1: error: expected declaration before '}' token
 };
 ^
cc1plus: warning: unrecognized command line option "-Wno-extern-c-compat"
cc1plus: warning: unrecognized command line option "-Wno-extern-c-compat"
make: *** [obj/local/armeabi/objs-debug/cocos2dcpp_shared/__/__/Classes/Chicken.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from jni/../../Classes/Road.h:13:0,
                 from jni/../../Classes/GameScene.h:13,
                 from jni/../../Classes/GameScene.cpp:9:
jni/../../Classes/Utils.h:19:17: error: 'cocos2d' is not a namespace-name
 using namespace cocos2d;
                 ^
jni/../../Classes/Utils.h:19:24: error: expected namespace-name before ';' token
 using namespace cocos2d;
                        ^
jni/../../Classes/Utils.h:23:12: error: 'Vector' does not name a type
     static Vector<SpriteFrame*> getSpriteFrames(const char *name, int from, int to);
            ^
jni/../../Classes/Utils.h:24:12: error: 'Animate' does not name a type
     static Animate* createAnimated(Vector<SpriteFrame*> frames, float speed);
            ^
jni/../../Classes/Utils.h:25:12: error: 'Animate' does not name a type
     static Animate* createAnimated(const char *name, int from, int to, float speed);
            ^
jni/../../Classes/Utils.h:29:27: error: 'Node' has not been declared
     static void drawPoint(Node *node, Vec2 position);
                           ^
jni/../../Classes/Utils.h:29:39: error: 'Vec2' has not been declared
     static void drawPoint(Node *node, Vec2 position);
                                       ^
jni/../../Classes/Utils.h:30:12: error: 'PhysicsBody' does not name a type
     static PhysicsBody* applyPhysicBody(Sprite *sprite, int type, int hitType);
            ^
jni/../../Classes/Utils.h:31:12: error: 'PhysicsBody' does not name a type
     static PhysicsBody* applyPhysicBody(Sprite *sprite, cocos2d::Size size, int type, int hitType);
            ^
jni/../../Classes/Utils.h:33:17: error: 'string' in namespace 'std' does not name a type
     static std::string formatTimer(int second);
                 ^
jni/../../Classes/Utils.h:35:23: error: 'Node' has not been declared
     static void pause(Node *node);
                       ^
jni/../../Classes/Utils.h:36:24: error: 'Node' has not been declared
     static void resume(Node *node);
                        ^
jni/../../Classes/Utils.h:37:35: error: 'Node' has not been declared
     static void removeAllChildren(Node *node);
                                   ^
jni/../../Classes/Utils.h:39:33: error: 'Node' has not been declared
     static void setGlobalZIndex(Node *node, int z);
                                 ^
jni/../../Classes/Utils.h:41:17: error: 'string' in namespace 'std' does not name a type
     static std::string readFile(std::string relativePath);
                 ^
jni/../../Classes/Utils.h:43:28: error: 'Node' has not been declared
     static void flashColor(Node *node, Color3B startColor, Color3B backColor, int blinkCount, float duration);
                            ^
jni/../../Classes/Utils.h:43:40: error: 'Color3B' has not been declared
     static void flashColor(Node *node, Color3B startColor, Color3B backColor, int blinkCount, float duration);
                                        ^
jni/../../Classes/Utils.h:43:60: error: 'Color3B' has not been declared
     static void flashColor(Node *node, Color3B startColor, Color3B backColor, int blinkCount, float duration);
                                                            ^
In file included from jni/../../Classes/Road.h:14:0,
                 from jni/../../Classes/GameScene.h:13,
                 from jni/../../Classes/GameScene.cpp:9:
jni/../../Classes/Lane.h:21:28: error: expected class-name before '{' token
 class LaneData : public Ref{
                            ^
jni/../../Classes/Lane.h:30:21: error: 'cocos2d' has not been declared
 class Lane : public cocos2d::Sprite{
                     ^
jni/../../Classes/Lane.h:30:30: error: expected '{' before 'Sprite'
 class Lane : public cocos2d::Sprite{
                              ^
jni/../../Classes/Lane.h:30:36: error: invalid type in declaration before '{' token
 class Lane : public cocos2d::Sprite{
                                    ^
jni/../../Classes/Lane.h:31:1: error: expected primary-expression before 'private'
 private:
 ^
jni/../../Classes/Lane.h:31:1: error: expected '}' before 'private'
jni/../../Classes/Lane.h:31:1: error: expected ',' or ';' before 'private'
jni/../../Classes/Lane.h:35:1: error: expected unqualified-id before 'public'
 public:
 ^
jni/../../Classes/Lane.h:43:10: error: expected unqualified-id before 'int'
     Lane(int type);
          ^
jni/../../Classes/Lane.h:43:10: error: expected ')' before 'int'
jni/../../Classes/Lane.h:44:10: error: expected unqualified-id before 'int'
     Lane(int type, int direction, int speed, float ratio);
          ^
jni/../../Classes/Lane.h:44:10: error: expected ')' before 'int'
jni/../../Classes/Lane.h:50:5: error: 'Vec2' does not name a type
     Vec2 getStartPoint();
     ^
jni/../../Classes/Lane.h:51:5: error: 'Vec2' does not name a type
     Vec2 getEndPoint();
     ^
jni/../../Classes/Lane.h:52:1: error: expected declaration before '}' token
 };
 ^
cc1plus: warning: unrecognized command line option "-Wno-extern-c-compat"
cc1plus: warning: unrecognized command line option "-Wno-extern-c-compat"
make: *** [obj/local/armeabi/objs-debug/cocos2dcpp_shared/__/__/Classes/GameScene.o] Error 1
make: Leaving directory`/Volumes/Data/AndroidProj/ChickenRun_v4/proj.android'
Ndk build failed!
Traceback (most recent call last):
  File "/Volumes/Data/AndroidProj/ChickenRun_v4/proj.android/build_native.py", line 45, in <module>
    build(opts.build_mode)
  File "/Volumes/Data/AndroidProj/ChickenRun_v4/proj.android/build_native.py", line 30, in build
    raise Exception("Build dynamic library for project [ " + app_android_root + " ] fails!")
Exception: Build dynamic library for project [ /Volumes/Data/AndroidProj/ChickenRun_v4/proj.android/../ ] fails!
</code>
# <br>

I think you guy can look at this image for short version of log
![screen shot 2015-07-29 at 12 03 48 am](https://cloud.githubusercontent.com/assets/3175469/8937895/6be477a0-3585-11e5-9f41-8a4d5cf57b83.png)

P/s: Sorry for long post

**Comment by purepure** [comment]
I resolve myself. 
Some class does not include #include "cocos2d.h". So I try to include that class to make it work
The most wired is about I can compile for ios normally but Android,
