### ISSUE TITLE
Adding COCOS_CONSOLE_ROOT environment variable fails with zsh on OSX 10.10.4

### ISSUE THREAD

**Issue by rebeccapaz** [cocos2d/cocos2d-x#13642]
On OSX 10.10.4, using zsh with Zach Holman's [dotfiles](https://github.com/holman/dotfiles), running `./setup.py` returns this error:

```
2.2.2 in cocos2d-x/ on v3
› ./setup.py

Setting up cocos2d-x...
->Check environment variable COCOS_CONSOLE_ROOT
  ->Search for environment variable COCOS_CONSOLE_ROOT...
    ->COCOS_CONSOLE_ROOT not found

  -> Add COCOS_CONSOLE_ROOT environment variable...
Traceback (most recent call last):
  File "./setup.py", line 707, in <module>
    opts.ndk_root, opts.android_sdk_root, opts.ant_root)
  File "./setup.py", line 665, in set_environment_variables
    self.set_console_root()
  File "./setup.py", line 473, in set_console_root
    COCOS_CONSOLE_ROOT, cocos_consle_root)
  File "./setup.py", line 206, in _set_environment_variable
    ret = self._set_environment_variable_unix(key, value)
  File "./setup.py", line 186, in _set_environment_variable_unix
    shutil.copy(self.file_used_for_setup, self.backup_file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 2] No such file or directory: '/Users/Rpaz/.zshrc.backup'
```

I tried running `touch ~/.zshrc.backup`, but it just gives me `touch: /Users/Rpaz/.zshrc.backup: No such file or directory`. `touch ~/.zshrc.backupa` works fine, though, which is kind of bizarre.

**Comment by drelaptop** [comment]
Not any developers concern this issue for more than 2 year, so just close it. please reopen if disagree.
@rpazyaquian
