### ISSUE TITLE
Immediate crash during init with 2 monitors connected to iMac

### ISSUE THREAD

**Issue by CodeAndWeb** [cocos2d/cocos2d-x#14679]
I have a crash directly while launching the "hello world" app on my iMac.

Cocos2d: 3.9
XCode: 7.2
MacOS: 10.11.2
Hardware: Retina iMac 27", 2nd Monitor

The app runs without any problems as soon as the second monitor is disconnected.

The code that's executed until the crash:

Main:

```
int main(int argc, char *argv[])
{
    AppDelegate app;
    return Application::getInstance()->run();
}
```

AppDelegate: initGLContextAttrs

```
void AppDelegate::initGLContextAttrs()
{
   GLContextAttrs glContextAttrs = {8, 8, 8, 8, 24, 8};
    GLView::setGLContextAttrs(glContextAttrs);
}
```

AppDelegate: applicationDidFinishLaunching

```
bool AppDelegate::applicationDidFinishLaunching()
{
    auto director = Director::getInstance();
    auto glview = director->getOpenGLView();
    if(!glview) {
#if (CC_TARGET_PLATFORM == CC_PLATFORM_WIN32) || (CC_TARGET_PLATFORM == CC_PLATFORM_MAC) || (CC_TARGET_PLATFORM == CC_PLATFORM_LINUX)
        glview = GLViewImpl::createWithRect("Cocos2dx-SpriteSheetTutorial", Rect(0, 0,  designResolutionSize.width, designResolutionSize.height));
#else
        glview = GLViewImpl::create("Cocos2dx-SpriteSheetTutorial");
#endif
        director->setOpenGLView(glview);
    }
}
```

The rest is in cocos2d-x.

The crashlog:

```
#0  0x00007fff9e5e3152 in strlen ()
#1  0x00007fff9e628a54 in __vfprintf ()
#2  0x00007fff9e6516c9 in __v2printf ()
#3  0x00007fff9e635915 in _vsnprintf ()
#4  0x00007fff9e6359ca in vsnprintf ()
#5  0x00000001005f3c72 in _glfwInputError ()
#6  0x00000001005f9aab in _glfwPlatformGetMonitors ()
#7  0x00000001005f3e75 in glfwInit ()
#8  0x0000000100572af8 in cocos2d::GLViewImpl::GLViewImpl() 
#9  0x0000000100572b35 in cocos2d::GLViewImpl::GLViewImpl() 
#10 0x00000001005739e4 in cocos2d::GLViewImpl::createWithRect(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cocos2d::Rect, float) at /Users/sk/Programming/_test_and_tutorials/Cocos2dx-SpriteSheetTutorial/Project/cocos2d/cocos/platform/desktop/CCGLViewImpl-desktop.cpp:312
#12 0x0000000100001f89 in AppDelegate::applicationDidFinishLaunching()
#13 0x00000001005c47e9 in cocos2d::Application::run() 
#14 0x0000000100003996 in main 
#15 0x0000000100001274 in start ()
```

**Comment by CodeAndWeb** [comment]
Update: The crash only happens when the displays are in mirror mode.
I also assume that it's a MacOS problem and not cocos2d-x.

**Comment by minggo** [comment]
I don't have issue with latest codes. I use MBP, and my environments are:
- Xcode 7.3.1
- Mac OS X: 10.11.6

We also upgraded GLFW, i am not sure if it is something related. So close this issue. Feel free to reopen it if you still has the issue.
