### ISSUE TITLE
Error in the compiler for android

### ISSUE THREAD

**Issue by alexandreservian** [cocos2d/cocos2d-x#15592]
hello guys, i am with a problem in the compiler for android, its generates this error:
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0
can someone help me?

**Comment by minggo** [comment]
You'd better describe what did you do step by step.

**Comment by alexandreservian** [comment]
I am trying build a app for android with the command: compile -p android.
I am using ubuntu 14.10, java version 1.7.0, cocos2dx 3.10, apache int 1.9 and android nkd r10e. However, when using command compile -p android, it generates the next error:

-pre-compile:

-compile:
    [javac] Compiling 3 source files to /home/servian/cocos2d-x-3.10/projects/HelloWorld/proj.android/bin/classes

-post-compile:

-obfuscate:

-dex:
      [dex] input: /home/servian/cocos2d-x-3.10/projects/HelloWorld/proj.android/bin/classes
      [dex] input: /home/servian/cocos2d-x-3.10/projects/HelloWorld/cocos2d/cocos/platform/android/java/bin/classes.jar
      [dex] input: /home/servian/cocos2d-x-3.10/projects/HelloWorld/cocos2d/cocos/platform/android/java/libs/android-async-http-1.4.8.jar
      [dex] Pre-Dexing /home/servian/cocos2d-x-3.10/projects/HelloWorld/cocos2d/cocos/platform/android/java/bin/classes.jar -> classes-5907b3ba09de7c15ca306dab37d55581.jar
       [dx] Exception in thread "main" java.lang.UnsupportedClassVersionError: com/android/dx/command/Main : Unsupported major.minor version 52.0
       [dx]     at java.lang.ClassLoader.defineClass1(Native Method)
       [dx]     at java.lang.ClassLoader.defineClass(ClassLoader.java:643)
       [dx]     at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
       [dx]     at java.net.URLClassLoader.defineClass(URLClassLoader.java:277)
       [dx]     at java.net.URLClassLoader.access$000(URLClassLoader.java:73)
       [dx]     at java.net.URLClassLoader$1.run(URLClassLoader.java:212)
       [dx]     at java.security.AccessController.doPrivileged(Native Method)
       [dx]     at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
       [dx]     at java.lang.ClassLoader.loadClass(ClassLoader.java:323)
       [dx]     at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:294)
       [dx]     at java.lang.ClassLoader.loadClass(ClassLoader.java:268)
       [dx] Could not find the main class: com.android.dx.command.Main. Program will exit.

BUILD FAILED
/home/servian/Android/Sdk/tools/ant/build.xml:888: The following error occurred while executing this line:
/home/servian/Android/Sdk/tools/ant/build.xml:890: The following error occurred while executing this line:
/home/servian/Android/Sdk/tools/ant/build.xml:902: The following error occurred while executing this line:
/home/servian/Android/Sdk/tools/ant/build.xml:283: null returned: 1

Total time: 5 seconds
Error running command, return code: 1.

**Comment by minggo** [comment]
According [the ticket](http://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0), your problem is similar with Java version mismatching. May be your computer also installed other Java versions, such as 1.8.

**Comment by skoolguy** [comment]
A similar problem happened to me too.

Try this...   Goto File > Project Structure 

open apps in the modules section (in the sidebar)
change the Build Tools Version from 24.0.1 to 23.0.3

**Comment by huangleon** [comment]
Android Build Tools works for me for same issue with different project.
I just delete Android SDK Build-tools 25.0.x from Android SDK Manager, and only 23.0.x left.
