### ISSUE TITLE
V3: cocos-console broken on windows

### ISSUE THREAD

**Issue by stammen** [cocos2d/cocos2d-x#15674]
V3: running cocos console on windows is broken on v3 branch. Generates a /.cocos\local_cfg.json file not found error. Should not crash if there is no config file.

```
C:\Users\stammen\github\cocos2d-x-v3>cocos new foo -l cpp -d projects
In order to continually innovate and improve Cocos products, Chukong Aipu may collect certain usage statistics from the software including but not limited to a unique identifier,  version number of the software, and information on which tools and/or services in Cocos products are being used and how they are being used. The data collected is examined in the aggregate to improve Cocos products and is maintained in accordance with Chukong Aipu's Privacy Policy.
Do you agree to sent the data? [Y]es, [N]o
y
Traceback (most recent call last):
  File "C:\Users\stammen\github\cocos2d-x-v3\tools\cocos2d-console\bin\/cocos.py", line 959, in <module>
    DataStatistic.show_stat_agreement()
  File "C:\Users\stammen\github\cocos2d-x-v3\tools\cocos2d-console\bin\/cocos.py", line 341, in show_stat_agreement
    cls.change_agree_stat(agreed)
  File "C:\Users\stammen\github\cocos2d-x-v3\tools\cocos2d-console\bin\/cocos.py", line 314, in change_agree_stat
    cls.set_cfg_value(cls.key_agreement_showed, True)
  File "C:\Users\stammen\github\cocos2d-x-v3\tools\cocos2d-console\bin\/cocos.py", line 303, in set_cfg_value
    f = open(cfg_file, 'w')
IOError: [Errno 2] No such file or directory: 'C:\\Users\\stammen/.cocos\\local_cfg.json'
C:\Users\stammen\github\cocos2d-x-v3>
```

**Comment by slackmoehrle** [comment]
This also happens on OS X and Linux.

```
(jtsm @ 15 ~/Chukong-Inc/cocos2d-x)  git:(upstream ⚡ v3) 1M $ cocos -v
In order to continually innovate and improve Cocos products, Chukong Aipu may collect certain usage statistics from the software including but not limited to a unique identifier,  version number of the software, and information on which tools and/or services in Cocos products are being used and how they are being used. The data collected is examined in the aggregate to improve Cocos products and is maintained in accordance with Chukong Aipu's Privacy Policy.
Do you agree to sent the data? [Y]es, [N]o
Y
Traceback (most recent call last):
  File "/Users/jtsm/Chukong-Inc/cocos2d-x/tools/cocos2d-console/bin/cocos.py", line 959, in <module>
    DataStatistic.show_stat_agreement()
  File "/Users/jtsm/Chukong-Inc/cocos2d-x/tools/cocos2d-console/bin/cocos.py", line 341, in show_stat_agreement
    cls.change_agree_stat(agreed)
  File "/Users/jtsm/Chukong-Inc/cocos2d-x/tools/cocos2d-console/bin/cocos.py", line 314, in change_agree_stat
    cls.set_cfg_value(cls.key_agreement_showed, True)
  File "/Users/jtsm/Chukong-Inc/cocos2d-x/tools/cocos2d-console/bin/cocos.py", line 303, in set_cfg_value
    f = open(cfg_file, 'w')
IOError: [Errno 2] No such file or directory: '/Users/jtsm/.cocos/local_cfg.json'
```

**Comment by stammen** [comment]
The user agreement code also introduces a new issue: https://github.com/cocos2d/cocos2d-x/issues/15675. There is now no way to run cocos new from jenkins to test building a newly generated game from the templates.

**Comment by chaoren** [comment]
Fix here: https://github.com/cocos2d/cocos2d-console/pull/345

**Comment by minggo** [comment]
@natural-law Could you please take a look.
About working with jenkins, it think it is better to pass a parameter to agree it or just have to select one time?

**Comment by natural-law** [comment]
> Fix here: cocos2d/cocos2d-console#345

@minggo This PR is a right solution. Sorry for my mistakes.
@chaoren Thanks for your contribution.

> About working with jenkins, it think it is better to pass a parameter to agree it or just have to select one time?

Yep, the agreement will only show once. For jenkins environment, the solution is: create a file `[USER_PATH]/.cocos/local_cfg.json` with content:

```
{
    "agreement_showed": true
}
```

**Comment by chaoren** [comment]
Just a little nit pick. The correct grammar should be `agreement_shown`.

**Comment by minggo** [comment]
Good catch @chaoren .

**Comment by natural-law** [comment]
Sorry for my poor English. I've fixed it.

**Comment by stammen** [comment]
PR https://github.com/cocos2d/cocos2d-console/pull/346 fixed the issue.
