### ISSUE TITLE
cocos2d-x v 3.11.1 Android SimpleAudioEngine preloadBackgroundMusic

### ISSUE THREAD

**Issue by lfmn83** [cocos2d/cocos2d-x#16038]
cocos2d-x v 3.11.1
NDK-r10c

I'm getting FileNotFoundException when I'm preloading background music for Android.

```
E/Cocos2dxMusic: error: assets/res/sounds/menu.ogg
java.io.FileNotFoundException: assets/res/sounds/menu.ogg
at android.content.res.AssetManager.openAssetFd(Native Method)
at android.content.res.AssetManager.openFd(AssetManager.java:329)
at org.cocos2dx.lib.Cocos2dxMusic.createMediaplayer(Cocos2dxMusic.java:253)
at org.cocos2dx.lib.Cocos2dxMusic.preloadBackgroundMusic(Cocos2dxMusic.java:86)
at org.cocos2dx.lib.Cocos2dxHelper.preloadBackgroundMusic(Cocos2dxHelper.java:231)
at org.cocos2dx.lib.Cocos2dxRenderer.nativeInit(Native Method)
at org.cocos2dx.lib.Cocos2dxRenderer.onSurfaceCreated(Cocos2dxRenderer.java:72)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1500)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
```

I'm using: `CocosDenshion::SimpleAudioEngine::getInstance()->preloadBackgroundMusic(FileUtils::getInstance()->fullPathForFilename("menu.ogg").c_str());`

Effects are OK and all files are in the same folder:  `CocosDenshion::SimpleAudioEngine::getInstance()->preloadEffect(FileUtils::getInstance()->fullPathForFilename("sound.wav").c_str());`

For iOS everthing is OK.

**Comment by lfmn83** [comment]
It was fixed in https://github.com/cocos2d/cocos2d-x/pull/15512
