### ISSUE TITLE
Can't install on OSX

### ISSUE THREAD

**Issue by Gargo** [cocos2d/cocos2d-x#16199]
according to readme:
MacBook-Pro-Apple:cocos2d-x-3.12 apple$ cocos new -l cpp -p com.gamefromscratch.gamename -d ~/Documents/Projects/cocos2d gamename
Traceback (most recent call last):
  File "/Users/apple/Downloads/cocos2d-x-3.12/tools/cocos2d-console/bin/cocos.py", line 22, in <module>
    import cocos_project
  File "/Users/apple/Downloads/cocos2d-x-3.12/tools/cocos2d-console/bin/cocos_project.py", line 4, in <module>
    import cocos
  File "/Users/apple/Downloads/cocos2d-x-3.12/tools/cocos2d-console/bin/cocos.py", line 936, in <module>
    language, encoding = locale.getlocale()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 562, in getlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

Iwanted just create iOS project but it doesn't work

**Comment by minggo** [comment]
@natural-law could you please take a look?

**Comment by natural-law** [comment]
I think it's a same problem with issue #16138 .

**Comment by Gargo** [comment]
@natural-law I saw that issue: echo $LANG on my macbook returns empty string. How to set it correctly?

**Comment by natural-law** [comment]
@Gargo You can try this: https://github.com/cocos2d/cocos2d-console/pull/363

**Comment by minggo** [comment]
@Gargo have you tried as @natural-law suggested? Can i close this issue?

**Comment by Gargo** [comment]
@minggo yes, it works, thanks. But anyways I think it should be added into readme file

**Comment by minggo** [comment]
@Gargo sounds good. Could you please send a PR for it? I think you can describe it better as a user.
