### ISSUE TITLE
Unable to run new project in Android on simulator (java.lang.UnsatisfiedLinkError)

### ISSUE THREAD

**Issue by aardvarkk** [cocos2d/cocos2d-x#16681]
- cocos2d-x version: 3.13.1
- devices test on: Nexus 5X API 24 x86 Simulator
- developing environments
  - NDK version: r10e
  - Android Studio 2.2.1

Steps to Reproduce:
1. Create a new game with cocos command line
2. Open project in Android Studio and try to run it in the simulator

The project appears to build correctly, but when it runs I get the following:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.mycompany.mygame, PID: 2377
                  java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.mycompany.mygame/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.mycompany.mygame/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.mycompany.mygame/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.mycompany.mygame/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.mycompany.mygame/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.mycompany.mygame/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.mycompany.mygame/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.mycompany.mygame/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.mycompany.mygame/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.mycompany.mygame/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.mycompany.mygame/files/instant-run/dex/slice-httpclient-4.4.1.1_e45b7e97b167eb0f325ecc7c99a2e335516a4fc8-classes.dex", dex file "/data/data/com.mycompany.mygame/files/instant-run/dex/slice-com.android.vending.expansion.zipfile_81feeb87f088c684d66d15573052d4b47e9094ec-classes.dex", dex file "/data/data/com.mycompany.mygame/files/instant-run/dex/slice-android-async-http-1.4.9_2db9220d863530828e9643744088f3298fc54ad0-classes.dex"],nativeLibraryDirectories=[/data/app/com.mycompany.mygame-2/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libMyGame.so"
                      at java.lang.Runtime.loadLibrary0(Runtime.java:972)
                      at java.lang.System.loadLibrary(System.java:1530)
                      at org.cocos2dx.lib.Cocos2dxActivity.onLoadNativeLibraries(Cocos2dxActivity.java:248)
                      at org.cocos2dx.lib.Cocos2dxActivity.onCreate(Cocos2dxActivity.java:264)
                      at android.app.Activity.performCreate(Activity.java:6664)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2599)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2707)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1460)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

**Comment by dumganhar** [comment]
Did you build a  shared library for `x86` architecture?
The cocos command is

``` bash
cocos run -p android --app-abi=x86
```

**Comment by aardvarkk** [comment]
I was able to get a build running from the command line as you mentioned, but it should be possible to build directly from Android Studio, right?

**Comment by dumganhar** [comment]
@aardvarkk , currently, Android Studio just build java code, so you need to build so file in command line by using the following command:

```
cocos compile -p android --app-abi=x86 --no-apk
```

Make sure so file is generated, then run it in Android Studio.

Yep, run in Android Studio directly with java & cpp code compilation is WIP, please refer to PR #15676 .

If my solution works for you, please close this issue. Thanks.

**Comment by aardvarkk** [comment]
The problem seems to be related to Android Studio, not really a problem with Cocos2d-x. I was getting into situations where the native code wasn't rebuilding itself even though it needed to be. Triggering a sequence of Invalidate Caches/Restart, Clean, Sync Gradle, and then Refresh Linked C++ Projects, then rebuilding again fixed the linker errors.

I think the critical step is to Refresh Linked C++ Projects. That seems to get Android Studio in a better position to realize that native code needs to be rebuilt.
