### ISSUE TITLE
run "cocos " in zsh is error

### ISSUE THREAD

**Issue by igoofyy** [cocos2d/cocos2d-x#17162]
- cocos2d-x version:3.9
- devices test on: iphone
- developing environments
   - NDK version: NO
   - Xcode version:Xcode8.2
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. when I run this command "cocos " .I get this error 
Traceback (most recent call last):
  File "/Users/goofy/coco/cocos2d-x-3.9/tools/cocos2d-console/bin/cocos.py", line 22, in <module>
    import cocos_project
  File "/Users/goofy/coco/cocos2d-x-3.9/tools/cocos2d-console/bin/cocos_project.py", line 4, in <module>
    import cocos
  File "/Users/goofy/coco/cocos2d-x-3.9/tools/cocos2d-console/bin/cocos.py", line 874, in <module>
    language, encoding = locale.getlocale()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 562, in getlocale
    return _parse_localename(localename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8

**Comment by slackmoehrle** [comment]
what if you add this to your shell startup config?
```sh
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```

**Comment by igoofyy** [comment]
Good job .Thanks
