### ISSUE TITLE
[Android] Cocos2dxSound has ConcurrentModificationException

### ISSUE THREAD

**Issue by dumganhar** [cocos2d/cocos2d-x#17474]
Reported at http://discuss.cocos2d-x.org/t/android-cocos2dxsound-has-concurrentmodificationexception/10461

Crash stack:
```
java.util.ConcurrentModificationException
at java.util.HashMap\$HashIterator.nextEntry(HashMap.java:792)
at java.util.HashMap\$EntryIterator.next(HashMap.java:829)
at java.util.HashMap\$EntryIterator.next(HashMap.java:827)
at org.cocos2dx.lib.Cocos2dxSound.setEffectsVolume(Unknown Source)
at org.cocos2dx.lib.Cocos2dxHelper.setEffectsVolume(Unknown Source)
at org.cocos2dx.lib.Cocos2dxRenderer.nativeRender(Native Method)
at org.cocos2dx.lib.Cocos2dxRenderer.onDrawFrame(Unknown Source)
at android.opengl.GLSurfaceView\$GLThread.guardedRun(GLSurfaceView.java:1463)
at android.opengl.GLSurfaceView\$GLThread.run(GLSurfaceView.java:1217)
```

- cocos2d-x version: v3.14
- devices test on: Android
- developing environments
   - NDK version: r10e
   - Xcode version: N/A
   - VS version: N/A
   - browser type and version: N/A

Steps to Reproduce:

1. Hard to reproduce, but the crash informations were collected from analysis system.

**Comment by dumganhar** [comment]
fixed at https://github.com/cocos2d/cocos2d-x/pull/17479
