### ISSUE TITLE
Android application crash using the latest code -- EGL_BAD_ATTRIBUTE

### ISSUE THREAD

**Issue by Rubonnek** [cocos2d/cocos2d-x#17642]
- cocos2d-x version: v3.15, git commit acc97516d8 plus patch #17641
- devices test on: LG G3 Stylus - Android 5.0.2
- developing environments
   - NDK version: r14b

Steps to Reproduce:

1. Create a new C++ project, compile for android and deploy to device:
 ````shell
cocos new -l cpp latesttest
cd latesttest
cocos run -p android --ap android-19 -m release -j`nproc` --ndk-toolchain arm-linux-androideabi-4.9
````
2. `adb logcat` will show the following error:
````
E/AndroidRuntime(22829): Process: org.cocos2dx.latesttest, PID: 22829
E/AndroidRuntime(22829): java.lang.RuntimeException: createContext failed: EGL_BAD_ATTRIBUTE
E/AndroidRuntime(22829): 	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1192)
E/AndroidRuntime(22829): 	at android.opengl.GLSurfaceView$EglHelper.throwEglException(GLSurfaceView.java:1183)
E/AndroidRuntime(22829): 	at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1033)
E/AndroidRuntime(22829): 	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1400)
E/AndroidRuntime(22829): 	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
D/Wear_Controller( 1847): Received broadcast action=android.intent.action.PACKAGE_ADDED and uri=org.cocos2dx.latesttest
W/ActivityManager(  732):   Force finishing activity org.cocos2dx.latesttest/org.cocos2dx.cpp.AppActivity
````

**Comment by vladcioaba** [comment]
I found it too, the crash occurred on Android 4.4.4. 
On Android 6.0.1 it works.
