### ISSUE TITLE
externalNativeBuildDebug

### ISSUE THREAD

**Issue by hetao1024768** [cocos2d/cocos2d-x#17728]
- cocos2d-x version: 3.15
- devices test on: macOS 10.12.4
- developing environments
   - NDK version: 14.1.3816874
   - Xcode version: 8.3.1
   - VS version: x
   - browser type and version: x
   - Android Studio: 2.3.1

Steps to Reproduce:

1.  open proj.android-studio -> run -> show logs
Executing tasks: [:tools:assembleDebug]

Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
:libcocos2dx:preBuild UP-TO-DATE
:libcocos2dx:preReleaseBuild UP-TO-DATE
:libcocos2dx:checkReleaseManifest
:libcocos2dx:prepareReleaseDependencies
:libcocos2dx:compileReleaseAidl UP-TO-DATE
:libcocos2dx:compileReleaseNdk UP-TO-DATE
:libcocos2dx:compileLint UP-TO-DATE
:libcocos2dx:copyReleaseLint UP-TO-DATE
:libcocos2dx:mergeReleaseShaders UP-TO-DATE
:libcocos2dx:compileReleaseShaders UP-TO-DATE
:libcocos2dx:generateReleaseAssets UP-TO-DATE
:libcocos2dx:mergeReleaseAssets UP-TO-DATE
:libcocos2dx:mergeReleaseProguardFiles UP-TO-DATE
:libcocos2dx:packageReleaseRenderscript UP-TO-DATE
:libcocos2dx:compileReleaseRenderscript UP-TO-DATE
:libcocos2dx:generateReleaseResValues UP-TO-DATE
:libcocos2dx:generateReleaseResources UP-TO-DATE
:libcocos2dx:packageReleaseResources UP-TO-DATE
:libcocos2dx:processReleaseManifest UP-TO-DATE
:libcocos2dx:generateReleaseBuildConfig
:libcocos2dx:processReleaseResources
:libcocos2dx:generateReleaseSources
:libcocos2dx:incrementalReleaseJavaCompilationSafeguard
:libcocos2dx:javaPreCompileRelease
:libcocos2dx:compileReleaseJavaWithJavac
:libcocos2dx:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).

注: 某些输入文件使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。
注: 某些输入文件使用了未经检查或不安全的操作。
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。

:libcocos2dx:processReleaseJavaRes UP-TO-DATE
:libcocos2dx:transformResourcesWithMergeJavaResForRelease
:libcocos2dx:transformClassesAndResourcesWithSyncLibJarsForRelease
:libcocos2dx:mergeReleaseJniLibFolders
:libcocos2dx:transformNativeLibsWithMergeJniLibsForRelease
:libcocos2dx:transformNativeLibsWithStripDebugSymbolForRelease
:libcocos2dx:transformNativeLibsWithSyncJniLibsForRelease
:libcocos2dx:bundleRelease
:tools:preBuild UP-TO-DATE
:tools:preDebugBuild UP-TO-DATE
:tools:checkDebugManifest
:tools:prepareDebugDependencies
:tools:compileDebugAidl UP-TO-DATE
:tools:compileDebugRenderscript
:tools:generateDebugBuildConfig UP-TO-DATE
:tools:generateDebugResValues UP-TO-DATE
:tools:generateDebugResources
:tools:mergeDebugResources UP-TO-DATE
:tools:processDebugManifest UP-TO-DATE
:tools:processDebugResources
:tools:generateDebugSources
:tools:incrementalDebugJavaCompilationSafeguard
:tools:javaPreCompileDebug
:tools:compileDebugJavaWithJavac
:tools:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:tools:generateJsonModelDebug UP-TO-DATE
:tools:externalNativeBuildDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tools:externalNativeBuildDebug'.
> Unexpected native build target tools. Valid values are: audioengine, extension, cpufeatures, box2d, cocos2dandroid, spine, vorbisidec, MyGame, network, flatbuffers, cocos2dxinternal, ui, recast, cocos3d, cocosbuilder, bullet, pvmp3dec, cocostudio, cocosdenshion

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.493 secs

i don't know how to solve this issue

**Comment by hetao1024768** [comment]
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':tools:externalNativeBuildDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:61)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:228)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:77)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:58)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:196)
	at org.gradle.initialization.DefaultGradleLauncher$3.execute(DefaultGradleLauncher.java:193)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:193)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:119)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:102)
	at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:71)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:50)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:43)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner$1.execute(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:169)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:106)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:56)
	at org.gradle.tooling.internal.provider.runner.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:75)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
	at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:44)
	at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:29)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.GradleException: Unexpected native build target tools. Valid values are: audioengine, extension, cpufeatures, box2d, cocos2dandroid, spine, vorbisidec, MyGame, network, flatbuffers, cocos2dxinternal, ui, recast, cocos3d, cocosbuilder, bullet, pvmp3dec, cocostudio, cocosdenshion
	at com.android.build.gradle.tasks.ExternalNativeBuildTask.build(ExternalNativeBuildTask.java:113)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
	... 78 more

**Comment by minggo** [comment]
@hetao1024768 how to reproduce it?

**Comment by hetao1024768** [comment]
@minggo When I first build it ,everything is ok. 
All troubles come with me when I found static librarys had disapeard (xxx.a xxx.a xxx.a)

**Comment by minggo** [comment]
Did you mean after first time, you met the issue using Android Studio to build the project? What did you do after first time?

**Comment by hetao1024768** [comment]
@minggo Yep, I use CMM to clean my OSX, after that I found the static librarys in ~/project-name/proj.android-studio/app/build/intermediates/ndkBuild/ were cleaned.

**Comment by minggo** [comment]
What's CMM? I think you can use Android Studio to rebuild the project.

**Comment by hetao1024768** [comment]
@minggo CMM is CleanMyMac.app , used for system maintenance. When I rebuild it, it cause this issue.

**Comment by minggo** [comment]
Sorry, i have no idea.

**Comment by hetao1024768** [comment]
@minggo so I get a new project to go on

**Comment by xahon** [comment]
@hetao1024768 did you solve this issue?
