### ISSUE TITLE
 couldn't find "libcocos2djs.so"

### ISSUE THREAD

**Issue by BetaTiger** [cocos2d/cocos2d-x#17881]
- cocos2d-x version:cocos crator 1.4.2
- devices test on:android 
- developing environments
   - NDK version: android-ndk-r14b-darwin-x86_64
   - Xcode version: xcode8.3.2
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. create a new hello_world projects
2. build->choose android->use default template ->build
3.use android studio2.3 import the proj.android-studio, after compile i click run button ,

The android device show me:"unfortunately ,hello_world has stoped". 
The android studio provide me the error log below:
05-30 03:52:39.242 7297-7297/org.cocos2d.helloworld E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: org.cocos2d.helloworld, PID: 7297
                                                                      java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/org.cocos2d.helloworld-1/base.apk", zip file "/data/app/org.cocos2d.helloworld-1/split_lib_dependencies_apk.apk", zip file "/data/app/org.cocos2d.helloworld-1/split_lib_slice_0_apk.apk", zip file "/data/app/org.cocos2d.helloworld-1/split_lib_slice_1_apk.apk", zip file "/data/app/org.cocos2d.helloworld-1/split_lib_slice_2_apk.apk", zip file "/data/app/org.cocos2d.helloworld-1/split_lib_slice_3_apk.apk", zip file "/data/app/org.cocos2d.helloworld-1/split_lib_slice_4_apk.apk", zip file "/data/app/org.cocos2d.helloworld-1/split_lib_slice_5_apk.apk", zip file "/data/app/org.cocos2d.helloworld-1/split_lib_slice_6_apk.apk", zip file "/data/app/org.cocos2d.helloworld-1/split_lib_slice_7_apk.apk", zip file "/data/app/org.cocos2d.helloworld-1/split_lib_slice_8_apk.apk", zip file "/data/app/org.cocos2d.helloworld-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/org.cocos2d.helloworld-1/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libcocos2djs.so"
                                                                          at java.lang.Runtime.loadLibrary(Runtime.java:367)
                                                                          at java.lang.System.loadLibrary(System.java:1076)
                                                                          at org.cocos2dx.lib.Cocos2dxActivity.onLoadNativeLibraries(Cocos2dxActivity.java:249)
                                                                          at org.cocos2dx.lib.Cocos2dxActivity.onCreate(Cocos2dxActivity.java:265)
                                                                          at org.cocos2dx.javascript.AppActivity.onCreate(AppActivity.java:40)
                                                                          at android.app.Activity.performCreate(Activity.java:6237)
                                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                          at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.Z

**Comment by minggo** [comment]
Please don't report creator issues here. You may report it in forum.

**Comment by minggo** [comment]
Can reflect it in https://github.com/cocos-creator/cocos2d-x-lite too. Creator uses a custom cocos2d-x version.
