### ISSUE TITLE
How can I sencond launch cocos2dx page

### ISSUE THREAD

**Issue by Modificator** [cocos2d/cocos2d-x#18073]
- cocos2d-x version: 3.15 lua
- devices test on: Android&iOS
- developing environments
   - NDK version:15.1.4119039
   - Xcode version: 8.3.3

I merged cocos2dx with native app,
first launch,close cocos2dx page,,it's OK.

But when I launch it again,it was crashed.

```
07-15 11:59:28.903 32203-1988/com.xxx.xxx.dev A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xf42fe344 in tid 1988 (GLThread 4189)
                                                                 
                                                                 [ 07-15 11:59:28.916   227:  227 W/         ]
                                                                 debuggerd: handling request: pid=32203 uid=10168 gid=10168 tid=1988
07-15 11:59:29.163 1992-1992/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-15 11:59:29.164 1992-1992/? A/DEBUG: LineageOS Version: '14.1-20170606-UNOFFICIAL-nx503a'
07-15 11:59:29.164 1992-1992/? A/DEBUG: Build fingerprint: 'nubia/NX503A/NX503A:4.4.2/KVT49L/eng.nubia.20150120.194044:user/release-keys'
07-15 11:59:29.164 1992-1992/? A/DEBUG: Revision: '0'
07-15 11:59:29.164 1992-1992/? A/DEBUG: ABI: 'arm'
07-15 11:59:29.164 1992-1992/? A/DEBUG: pid: 32203, tid: 1988, name: GLThread 4189  >>> com.xxx.xxx.dev <<<
07-15 11:59:29.164 1992-1992/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xf42fe344
07-15 11:59:29.164 1992-1992/? A/DEBUG:     r0 f42fe338  r1 94159c68  r2 948b35a0  r3 94159c78
07-15 11:59:29.164 1992-1992/? A/DEBUG:     r4 948ac1c0  r5 948ac1c0  r6 94159c70  r7 97619dc8
07-15 11:59:29.165 1992-1992/? A/DEBUG:     r8 97619f88  r9 95155400  sl 00000000  fp 97619dc4
07-15 11:59:29.165 1992-1992/? A/DEBUG:     ip 8dfb2169  sp 97619d80  lr 8dfb217f  pc 8dfc3008  cpsr 800f0030
07-15 11:59:29.177 1992-1992/? A/DEBUG: backtrace:
07-15 11:59:29.177 1992-1992/? A/DEBUG:     #00 pc 010c6008  /data/app/com.xxx.xxx.dev-1/lib/arm/libcocos2dlua.so
07-15 11:59:29.177 1992-1992/? A/DEBUG:     #01 pc 010b517b  /data/app/com.xxx.xxx.dev-1/lib/arm/libcocos2dlua.so (lua_rawget+18)
07-15 11:59:29.177 1992-1992/? A/DEBUG:     #02 pc 00c7382c  /data/app/com.xxx.xxx.dev-1/lib/arm/libcocos2dlua.so (tolua_module+56)
07-15 11:59:29.177 1992-1992/? A/DEBUG:     #03 pc 00a1cd41  /data/app/com.xxx.xxx.dev-1/lib/arm/libcocos2dlua.so (_Z23register_all_DataParamsP9lua_State+28)
07-15 11:59:29.177 1992-1992/? A/DEBUG:     #04 pc 00a18179  /data/app/com.xxx.xxx.dev-1/lib/arm/libcocos2dlua.so (_ZN11AppDelegate29applicationDidFinishLaunchingEv+92)
07-15 11:59:29.177 1992-1992/? A/DEBUG:     #05 pc 00a24409  /data/app/com.xxx.xxx.dev-1/lib/arm/libcocos2dlua.so (_ZN7cocos2d11Application3runEv+20)
07-15 11:59:29.177 1992-1992/? A/DEBUG:     #06 pc 00a2829f  /data/app/com.xxx.xxx.dev-1/lib/arm/libcocos2dlua.so (Java_org_cocos2dx_lib_Cocos2dxRenderer_nativeInit+170)
07-15 11:59:29.177 1992-1992/? A/DEBUG:     #07 pc 00fce145  /data/app/com.xxx.xxx.dev-1/oat/arm/base.odex (offset 0xea5000)
                                        
                                        
                                        [ 07-15 11:59:30.553   227:  227 W/         ]
                                        debuggerd: resuming target 32203
07-15 11:59:30.595 815-2004/system_process W/ActivityManager:   Force finishing activity com.xxx.xxx.dev/org.cocos2dx.lua.AppActivity
07-15 11:59:30.598 815-2004/system_process W/ActivityManager:   Force finishing activity com.xxx.xxx.dev/com.xxx.xxx.MainActivity
07-15 11:59:30.603 815-1107/system_process D/GraphicsStats: Buffer count: 12
07-15 11:59:30.605 815-828/system_process I/WindowManager: WIN DEATH: Window{cda4839 u0 SurfaceView - com.xxx.xxx.dev/org.cocos2dx.lua.AppActivity}
07-15 11:59:30.607 815-10589/system_process I/WindowManager: WIN DEATH: Window{fb4953d u0 com.xxx.xxx.dev/org.cocos2dx.lua.AppActivity}
07-15 11:59:30.610 815-10524/system_process I/WindowManager: WIN DEATH: Window{7715928 u0 com.xxx.xxx.dev/com.xxx.xxx.MainActivity}
07-15 11:59:30.636 281-281/? I/Zygote: Process 32203 exited due to signal (11)
07-15 11:59:30.654 815-851/system_process I/BootReceiver: Copying /data/tombstones/tombstone_04 to DropBox (SYSTEM_TOMBSTONE)
07-15 11:59:30.665 815-10766/system_process I/ActivityManager: Process com.xxx.xxx.dev (pid 32203) has died
07-15 11:59:30.665 815-10766/system_process D/ActivityManager: cleanUpApplicationRecord -- 32203
07-15 11:59:30.666 815-10766/system_process W/ActivityManager: Scheduling restart of crashed service com.xxx.xxx.dev/com.xxx.xxx.imservice.service.MsgService in 1000ms
07-15 11:59:30.773 815-834/system_process E/Notification: setLatestEventInfo() is deprecated and you should feel deprecated.
                                                          java.lang.Throwable
                                                              at android.app.Notification.setLatestEventInfo(Notification.java:2083)
                                                              at com.android.server.am.ActivityManagerService$MainHandler.handleMessage(ActivityManagerService.java:2363)
                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                              at android.os.Looper.loop(Looper.java:154)
                                                              at android.os.HandlerThread.run(HandlerThread.java:61)
                                                              at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

I changed `Cocos2dxHelper` to keep app alive
```java
    public static void terminateProcess() {
        sActivity.finish();
    }
```

**Comment by minggo** [comment]
It is not supported.

**Comment by playscforever** [comment]
@minggo why？
