### ISSUE TITLE
EditBox crash

### ISSUE THREAD

**Issue by angelvet** [cocos2d/cocos2d-x#18364]
- cocos2d-x version: v3.16
- devices test on: Motorola Xoom
- developing environments
   - NDK version: r12b
   - Xcode version:
   - VS version:2015
   - browser type and version:

After upgrading my project to cocos2d-x v3.16 my game started to crash occasionally when I update text in EditBox.

Steps to Reproduce:

1. Set focus to EditBox, virtual keyboard pops out
2. Update value in EditBox and hit Enter key on virtual keyboard

EditBox created using code like this:
` 
auto numberEditBox = EditBox::create(...); 
numberEditBox->setInputMode(EditBox::InputMode::NUMERIC); 
numberEditBox->setMaxLength(2); 
`

FATAL EXCEPTION: main
java.lang.IndexOutOfBoundsException: setSpan (4 ... 4) ends beyond length 3
at android.text.SpannableStringBuilder.checkRange(SpannableStringBuilder.java:1016)
at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:592)
at android.text.SpannableStringBuilder.setSpan(SpannableStringBuilder.java:588)
at android.text.Selection.setSelection(Selection.java:76)
android.text.Selection.setSelection(Selection.java:87)
at android.widget.EditText.setSelection(EditText.java:94)
at org.cocos2dx.lib.Cocos2dxEditBoxHelper$9.run(Cocos2dxEditBoxHelper.java:339)
at android.os.Handler.handleCallback(Handler.java:615)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4896)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
at dalvik.system.NativeStart.main(Native Method)

**Comment by dumganhar** [comment]
It was fixed at https://github.com/cocos2d/cocos2d-x/pull/18330 .
This patch isn't in v3.16.

**Comment by angelvet** [comment]
Thanks
