### ISSUE TITLE
Change debug apk path 

### ISSUE THREAD

**Issue by giangm9** [cocos2d/cocos2d-x#18506]
- cocos2d-x version:
cocos2d-x-3.16
Cocos Console 2.3

- devices test on: Android
- developing environments
   - NDK version: android-ndk-r16
   - Xcode version: none
   - VS version: none
   - browser type and version: none
i build cocos to android, use android-studio project, android-platforms-tool 25
ubuntu 17.10
Steps to Reproduce:

1. create a new cocos project 
2. `cocos run -p android --android-studio`
3. 
```
Traceback (most recent call last):
  File "/home/gl/tools/cocos2d-x-3.16/tools/cocos2d-console/bin/cocos.py", line 1072, in <module>
    run_plugin(command, argv, plugins)
  File "/home/gl/tools/cocos2d-x-3.16/tools/cocos2d-console/bin/cocos.py", line 958, in run_plugin
    dep_name, argv, plugins)
  File "/home/gl/tools/cocos2d-x-3.16/tools/cocos2d-console/bin/cocos.py", line 958, in run_plugin
    dep_name, argv, plugins)
  File "/home/gl/tools/cocos2d-x-3.16/tools/cocos2d-console/bin/cocos.py", line 961, in run_plugin
    plugin.run(argv, dependencies_objects)
  File "/home/gl/tools/cocos2d-x-3.16/tools/cocos2d-console/plugins/plugin_compile/project_compile.py", line 1646, in run
    self.build_android()
  File "/home/gl/tools/cocos2d-x-3.16/tools/cocos2d-console/plugins/plugin_compile/project_compile.py", line 581, in build_android
    self.apk_path = builder.do_build_apk(build_mode, self._no_apk, output_dir, self._custom_step_args, self._ap, self)
  File "/home/gl/tools/cocos2d-x-3.16/tools/cocos2d-console/plugins/plugin_compile/build_android.py", line 669, in do_build_apk
    shutil.copy(gen_apk_path, output_dir)
  File "/usr/lib/python2.7/shutil.py", line 133, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 96, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/home/gl/projects/altp-gl/proj.android-studio/app/build/outputs/apk/altp-gl-debug.apk'
```
4. I modified file "/home/gl/tools/cocos2d-x-3.16/tools/cocos2d-console/plugins/plugin_compile/project_compile.py", 
line 607, change          
```py
gen_apk_folder = os.path.join(self.app_android_root, 'app/build/outputs/apk')
```
to 
```py
gen_apk_folder = os.path.join(self.app_android_root, 'app/build/outputs/apk/debug')
```
and it run successfuly

**Comment by madebymozart** [comment]
I am working on a PR right now to mane cocos handle prebuilts with Android much better for the future and hopefully 3.17
