### ISSUE TITLE
cocos command 3.17 breaks compatibility

### ISSUE THREAD

**Issue by ghost** [cocos2d/cocos2d-x#18851]
- cocos2d-x version: 3.16
- devices test on:
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. set cocos to cocos2d-x 3.17 version
2. create test project with cocos2d-x 3.16
3. `cocos run -p android`

```
Traceback (most recent call last):
  File "/Users/admin/repos/cocos2d-x/tools/cocos2d-console/bin/cocos.py", line 1072, in <module>
    run_plugin(command, argv, plugins)
  File "/Users/admin/repos/cocos2d-x/tools/cocos2d-console/bin/cocos.py", line 958, in run_plugin
    dep_name, argv, plugins)
  File "/Users/admin/repos/cocos2d-x/tools/cocos2d-console/bin/cocos.py", line 958, in run_plugin
    dep_name, argv, plugins)
  File "/Users/admin/repos/cocos2d-x/tools/cocos2d-console/bin/cocos.py", line 961, in run_plugin
    plugin.run(argv, dependencies_objects)
  File "/Users/admin/repos/cocos2d-x/tools/cocos2d-console/plugins/plugin_compile/project_compile.py", line 1522, in run
    self.build_android()
  File "/Users/admin/repos/cocos2d-x/tools/cocos2d-console/plugins/plugin_compile/project_compile.py", line 540, in build_android
    self.apk_path = builder.do_build_apk(build_mode, self._no_apk, self._no_sign, output_dir, self._custom_step_args, self._ap, self)
  File "/Users/admin/repos/cocos2d-x/tools/cocos2d-console/plugins/plugin_compile/build_android.py", line 559, in do_build_apk
    self.gradle_build_apk(mode, android_platform, compile_obj)
  File "/Users/admin/repos/cocos2d-x/tools/cocos2d-console/plugins/plugin_compile/build_android.py", line 361, in gradle_build_apk
    f = open(check_file)
IOError: [Errno 2] No such file or directory: '/Users/admin/test/cpp316/proj.android/app/build.gradle'
```

**Comment by drelaptop** [comment]
refer to the release notes, https://github.com/cocos2d/cocos2d-x/blob/v3/docs/RELEASE_NOTES.md#remove-outdated

> Google officially deprecated ant build support starting in Android SDK Tools 25.3.0. The old ant based proj.android and been dropped and now proj.android is an Android Studio project. The default architecture is changed from armeabi to armeabi-v7a.

So, it breaks compatibility. I don't think it's a bad behavior, just a improvement. you should use the cocos console inside cocos2d-x 3.16 when you build 3.16 test project, 3.17 same.
