### ISSUE TITLE
3.16 version helloworld project crash when add SplashActivity 

### ISSUE THREAD

**Issue by pjdd** [cocos2d/cocos2d-x#18884]
- cocos2d-x version: 3.16
- devices test on: android device
- developing environments
   - NDK version:   r10e
   - Xcode version:  9.1
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. I create two helloword projects by cocos commond,the first project I didn’t set “PROJECT_NAME”, when i use SplashActivity to be LAUNCHER activity and then AppActivity the project is ok and not crash,But in the second project I set “PROJECT_NAME” with my project name and then the second project is crash.   the  message is  below

2. E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: cn.gamejelly.gong2ming, PID: 16658
                  java.lang.RuntimeException: Unable to destroy activity {cn.gamejelly.gong2ming/org.cocos2dx.lua.AppActivity}: java.lang.NullPointerException
                      at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3823)
                      at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3841)
                      at android.app.ActivityThread.access$1400(ActivityThread.java:174)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1451)
                      at android.os.Handler.dispatchMessage(Handler.java:110)
                      at android.os.Looper.loop(Looper.java:222)
                      at android.app.ActivityThread.main(ActivityThread.java:5484)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.lang.NullPointerException
                      at org.cocos2dx.lib.Cocos2dxHelper.runOnGLThread(Cocos2dxHelper.java:109)
                      at org.cocos2dx.lib.Cocos2dxAudioFocusManager.unregisterAudioFocusListener(Cocos2dxAudioFocusManager.java:121)
                      at org.cocos2dx.lib.Cocos2dxActivity.onDestroy(Cocos2dxActivity.java:212)
                      at org.cocos2dx.lua.AppActivity.onDestroy(AppActivity.java:58)
                      at android.app.Activity.performDestroy(Activity.java:5635)
                      at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1119)
                      at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3810)
                      at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3841) 
                      at android.app.ActivityThread.access$1400(ActivityThread.java:174) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1451) 
                      at android.os.Handler.dispatchMessage(Handler.java:110) 
                      at android.os.Looper.loop(Looper.java:222) 
                      at android.app.ActivityThread.main(ActivityThread.java:5484) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:860) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:676) 
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by pjdd** [comment]
![image](https://user-images.githubusercontent.com/2290632/41148867-9b95eae8-6b3c-11e8-87eb-9450e4e68489.png)

Because of Cocos2dxActivity class   function 
Comment it and it's  ok

**Comment by drelaptop** [comment]
I think PR https://github.com/cocos2d/cocos2d-x/pull/19010 is a better solution. @pjdd
