### ISSUE TITLE
unable to detect APK file

### ISSUE THREAD

**Issue by mosesliao** [cocos2d/cocos2d-x#18900]
- cocos2d-x version: 3.16
- devices test on:
- developing environments
   - NDK version: r13b
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:

1. Run below Dockerfile
```
FROM ubuntu

RUN apt-get -y update
RUN apt-get -y install software-properties-common openssl git locales ant unzip g++ libgdk-pixbuf2.0-dev python-pip cmake libx11-dev libxmu-dev libglu1-mesa-dev libgl2ps-dev libxi-dev libzip-dev libpng-dev libcurl4-gnutls-dev libfontconfig1-dev libsqlite3-dev libglew-dev libssl-dev libgtk-3-dev libglfw3 libglfw3-dev xorg-dev

ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV LC_ALL en_US.UTF-8

# Install Java.
RUN \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /var/cache/oracle-jdk8-installer && \
  apt install oracle-java8-set-default

# Define commonly used JAVA_HOME variable
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle

RUN cd /opt && \
    wget -q https://dl.google.com/android/repository/android-ndk-r13b-linux-x86_64.zip && \
    unzip *ndk*linux*.zip && \
    rm *ndk*linux*.zip

ENV NDK_ROOT /opt/android-ndk-r13b

RUN mkdir -p /opt/android-sdk && cd /opt/android-sdk && \
    wget -q https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip && \
    unzip *tools*linux*.zip && \
    rm *tools*linux*.zip

RUN ls -lah /opt/
ENV ANDROID_SDK_ROOT /opt/android-sdk
ENV PATH="$ANDROID_SDK_ROOT/tools/bin:${PATH}"

# ADD license_accepter.sh /opt/
RUN sdkmanager --licenses

RUN echo 'y' | sdkmanager 'build-tools;27.0.3' 'platforms;android-25'

RUN git clone https://github.com/cocos2d/cocos2d-x.git /cocos2dx
RUN cd /cocos2dx && git checkout cocos2d-x-3.16
RUN /cocos2dx/download-deps.py --remove-download yes
RUN cd /cocos2dx && git submodule update --init

ENV COCOS_X_ROOT /cocos2dx
ENV COCOS_CONSOLE_ROOT /cocos2dx/tools/cocos2d-console/bin
ENV COCOS_TEMPLATE_ROOT /cocos2dx/templates
ENV ANT_ROOT /usr/bin/ant

ENV PATH="/cocos2dx/tools/cocos2d-console/bin:${PATH}"
ENV PATH="/cocos2dx/template:${PATH}"

RUN cd /cocos2dx && ./setup.py

RUN apt-get -y autoclean && apt-get -y autoremove

# Testing for cocos2dx
RUN cd /cocos2dx/build && ./install-deps-linux.sh && mkdir linux-build && \
    cd linux-build && cmake ../..

# Define default command.
CMD ["bash"]

#entrypoint
WORKDIR /project

COPY . /project

RUN cd /project/Cocos2dx && cocos compile -p android --android-studio  --agreement 'n'
```
2. I got this error
```
BUILD SUCCESSFUL in 7m 49s
54 actionable tasks: 3 executed, 51 up-to-date
Traceback (most recent call last):
  File "/cocos2dx/tools/cocos2d-console/bin/cocos.py", line 1072, in <module>
    run_plugin(command, argv, plugins)
  File "/cocos2dx/tools/cocos2d-console/bin/cocos.py", line 961, in run_plugin
    plugin.run(argv, dependencies_objects)
  File "/cocos2dx/tools/cocos2d-console/plugins/plugin_compile/project_compile.py", line 1646, in run
    self.build_android()
  File "/cocos2dx/tools/cocos2d-console/plugins/plugin_compile/project_compile.py", line 581, in build_android
    self.apk_path = builder.do_build_apk(build_mode, self._no_apk, output_dir, self._custom_step_args, self._ap, self)
  File "/cocos2dx/tools/cocos2d-console/plugins/plugin_compile/build_android.py", line 669, in do_build_apk
    shutil.copy(gen_apk_path, output_dir)
  File "/usr/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/project/Cocos2dx/proj.android-studio/app/build/outputs/apk/Cocos2dx-debug.apk
```

**Comment by formatCvt** [comment]
if your project uses apk split you should add option to build universal apk and remove `-universal` from apk name.

**Comment by crazyhappygame** [comment]
@liaogz82
1. very nice docker file.
To download sdk, ndk there is https://github.com/cocos2d/cocos2d-x/blob/v3/tools/appveyor-scripts/setup_android.py . you can check usage in appveyor, Travis  ci. It works for Mac, Linux and windows
2. Consider use "gradlew assembleRelease" instead of cocos command
3. Most probably problem fixed in latest cocos2d-x.3.17

**Comment by mosesliao** [comment]
yes i managed to get it to work
