### ISSUE TITLE
UnsatisfiedLinkError: dlopen failed: cannot locate symbol “__aeabi_memclr” on devices with android 6.0

### ISSUE THREAD

**Issue by bolso80** [cocos2d/cocos2d-x#19125]
When I run my app on some devices (ZenPad 8.0, Moto G (3rd Gen), Galaxy J2 Prim), all with android 6.0, on runtime has this error:

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol “__aeabi_memclr” referenced by “/data/app/com.company.android.myapp-1/lib/arm/libcocos2dcpp.so”…
at java.lang.Runtime.loadLibrary(Runtime.java:372)
at java.lang.System.loadLibrary(System.java:1076)
at org.cocos2dx.lib.Cocos2dxActivity.d(Unknown Source)
at org.cocos2dx.lib.Cocos2dxActivity.onCreate

Some specs:

PROP_TARGET_SDK_VERSION=26
PROP_COMPILE_SDK_VERSION=26
PROP_MIN_SDK_VERSION=19
PROP_APP_ABI=armeabi-v7a:arm64-v8a

**Comment by ayarami** [comment]
Cocos2dx version?
Can you provide a demo project that we can reproduce those errors?
All devices with android 6.0 are affected?
developing environments? AS or Eclipse?
NDK version?

pls describe your issue in detail.

**Comment by gantana** [comment]
Hi! thanks for the help, we are trying to fix this bug for days now.

Cocos2dx version?
3.17

Can you provide a demo project that we can reproduce those errors?
At the moment we can't reproduce the problem in a demo project, actually we don't have the problem in an empty project.

All devices with android 6.0 are affected?
Not all devices are affected, for example xiaomi redmi 3s with Android 6.0.1 is working.

developing environments? AS or Eclipse?
AS

NDK version?
r17b

We are thinking that could be related to the platform Version of the ndk in gradle configuration. But at the moment we couldn't figure out how to properly set this.

Thanks in advance!

**Comment by minggo** [comment]
API 26 is android 8.0? You compiled with Android SDK 8.0, but run on Android 6.0, then it may have problem. So i think you have to change the PROP_COMPILE_SDK_VERSION to 23.
