### ISSUE TITLE
Android crashes when the game goes into the background

### ISSUE THREAD

**Issue by mkideal** [cocos2d/cocos2d-x#19162]
- cocos2d-x version: 3.17
- devices test on: HuaWei Honor 6x (Android 7.0)
- developing environments
   - NDK version: r16b
   - Xcode version:
   - VS version:
   - browser type and version:
   - Android Studio version: 3.1.4
   - PROP_APP_ABI=arm64-v8a:armeabi-v7a

Steps to Reproduce:

1. Lauch game successfully, but crashed while received a notification
```
11-10 21:32:08.463 3263-3287/? E/AndroidRuntime: FATAL EXCEPTION: GLThread 842
    Process: com.xxxxxxxx.xxx, PID: 3263
    java.lang.UnsatisfiedLinkError: No implementation found for void org.cocos2dx.lib.c.b(int) (tried Java_org_cocos2dx_lib_c_b and Java_org_cocos2dx_lib_c_b__I)
        at org.cocos2dx.lib.c.b(Native Method)
        at org.cocos2dx.lib.c.a(Unknown Source)
        at org.cocos2dx.lib.g.run(Unknown Source)
        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1507)
        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1267)
11-10 21:32:08.477 3263-3287/? I/Process: Sending signal. PID: 3263 SIG: 9
```

**Comment by mkideal** [comment]
In fact, as long as you switch to the background, it will crash. But this only happens in release mode. Modifying the configuration of the release part of build.gradle can solve this problem.

```
buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
}
```

`minifyEnabled` switch to `false`
`shrinkResources` switch to `false`
