### ISSUE TITLE
android ssl problem: Certificate doesn't match any of the subject alternative names

### ISSUE THREAD

**Issue by fresair** [cocos2d/cocos2d-x#19829]
- cocos2d-x version:3.17.2
- devices test on:samsung gt-n7100
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:
same problem as
https://stackoverflow.com/questions/39762760/javax-net-ssl-sslexception-certificate-doesnt-match-any-of-the-subject-alterna

seems httpclient version4.4.1.1  is too old

**Comment by minggo** [comment]
@PatriceJiang please take a look.

**Comment by fresair** [comment]
06-13 19:48:46.218 29126-30949/com.aaagame.vegaswildslots W/System.err: javax.net.ssl.SSLException: Certificate for <down.abcd.com> doesn't match any of the subject alternative names: [blo.abcd.com]
06-13 19:48:46.223 29126-30949/com.aaagame.vegaswildslots W/System.err:     at cz.msebera.android.httpclient.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:164)
06-13 19:48:46.223 29126-30949/com.aaagame.vegaswildslots W/System.err:     at cz.msebera.android.httpclient.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:61)
06-13 19:48:46.223 29126-30949/com.aaagame.vegaswildslots W/System.err:     at cz.msebera.android.httpclient.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:140)
06-13 19:48:46.223 29126-30949/com.aaagame.vegaswildslots W/System.err:     at cz.msebera.android.httpclient.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:114)
06-13 19:48:46.223 29126-30949/com.aaagame.vegaswildslots W/System.err:     at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.verifyHostname(SSLSocketFactory.java:569)
06-13 19:48:46.223 29126-30949/com.aaagame.vegaswildslots W/System.err:     at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:544)
06-13 19:48:46.223 29126-30949/com.aaagame.vegaswildslots W/System.err:     at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:409)
06-13 19:48:46.223 29126-30949/com.aaagame.vegaswildslots W/System.err:     at cz.msebera.android.httpclient.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:479)
06-13 19:48:46.223 29126-30949/com.aaagame.vegaswildslots W/System.err:     at cz.msebera.android.httpclient.conn.scheme.SchemeSocketFactoryAdaptor.connectSocket(SchemeSocketFactoryAdaptor.java:66)
06-13 19:48:46.223 29126-30949/com.aaagame.vegaswildslots W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:177)
06-13 19:48:46.223 29126-30949/com.aaagame.vegaswildslots W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
06-13 19:48:46.223 29126-30949/com.aaagame.vegaswildslots W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
06-13 19:48:46.223 29126-30949/com.aaagame.vegaswildslots W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
06-13 19:48:46.223 29126-30949/com.aaagame.vegaswildslots W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
06-13 19:48:46.223 29126-30949/com.aaagame.vegaswildslots W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:879)
06-13 19:48:46.223 29126-30949/com.aaagame.vegaswildslots W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
06-13 19:48:46.223 29126-30949/com.aaagame.vegaswildslots W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
06-13 19:48:46.223 29126-30949/com.aaagame.vegaswildslots W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
06-13 19:48:46.223 29126-30949/com.aaagame.vegaswildslots W/System.err:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
06-13 19:48:46.228 29126-30949/com.aaagame.vegaswildslots W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
06-13 19:48:46.228 29126-30949/com.aaagame.vegaswildslots W/System.err:     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
06-13 19:48:46.228 29126-30949/com.aaagame.vegaswildslots W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
06-13 19:48:46.228 29126-30949/com.aaagame.vegaswildslots W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
06-13 19:48:46.228 29126-30949/com.aaagame.vegaswildslots W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
06-13 19:48:46.228 29126-30949/com.aaagame.vegaswildslots W/System.err:     at java.lang.Thread.run(Thread.java:856)
06-13 19:48:46.318 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 44038; current position 44110
06-13 19:48:46.683 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 44410; current position 44481
06-13 19:48:47.068 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 44781; current position 44853
06-13 19:48:47.433 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 45153; current position 45224
06-13 19:48:47.728 29126-29126/com.aaagame.vegaswildslots V/AsyncHttpRH: Request retry no. 2
06-13 19:48:47.808 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 45524; current position 45596
06-13 19:48:48.173 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 45896; current position 45967
06-13 19:48:48.538 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 46267; current position 46339
06-13 19:48:48.908 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 46639; current position 46710
06-13 19:48:49.293 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 47010; current position 47082
06-13 19:48:49.338 29126-29128/com.aaagame.vegaswildslots D/dalvikvm: GC_CONCURRENT freed 1900K, 18% free 30843K/37575K, paused 14ms+8ms, total 132ms
06-13 19:48:49.338 29126-30949/com.aaagame.vegaswildslots D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 31ms
06-13 19:48:49.338 29126-29390/com.aaagame.vegaswildslots D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 26ms
06-13 19:48:49.658 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 47382; current position 47453
06-13 19:48:50.023 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 47753; current position 47825
06-13 19:48:50.568 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 300; current position 320
06-13 19:48:50.893 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 620; current position 692
06-13 19:48:51.258 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 992; current position 1063
06-13 19:48:51.633 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 1363; current position 1435
06-13 19:48:52.003 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 1735; current position 1806
06-13 19:48:52.373 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 2106; current position 2178
06-13 19:48:52.743 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 2478; current position 2549
06-13 19:48:53.113 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 2849; current position 2921
06-13 19:48:53.503 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 3221; current position 3293
06-13 19:48:53.873 29126-29481/com.aaagame.vegaswildslots W/libOpenSLES: Missed SL_PLAYEVENT_HEADATNEWPOS for position 3593; current position 3664


some error log, I change the domain name a bit.

**Comment by PatriceJiang** [comment]
I think the exception message is quite clear.  You can re-generate your certificate appended with the new domain. I am not familiar with letsencrypt, and hope this link can help you https://certbot.eff.org/docs/using.html#re-creating-and-updating-existing-certificates @fresair

**Comment by fresair** [comment]
@PatriceJiang  thanks for reply. we will check the link you provide.
Currently we use root Certificate (*.abcd.com) which I think it should be met with <down.abcd.com> and [blo.abcd.com]
The code work fine with phones using android 9
but in phone running android 4.4. the above error message showes

and i have provided the link https://stackoverflow.com/questions/39762760/javax-net-ssl-sslexception-certificate-doesnt-match-any-of-the-subject-alterna

it seems like the same problem
it  says that " use HttpClient 4.4 then you need to specify host verifier (NoopHostnameVerifier) to allow accepting certificates from different hosts:
SSLConnectionSocketFactory scsf = SSLConnectionSocketFactory(
     SSLContexts.custom().loadTrustMaterial(null, new TrustSelfSignedStrategy()).build(), 
        NoopHostnameVerifier.INSTANCE)
httpclient = HttpClients.custom().setSSLSocketFactory(scsf).build()
"

So any ideas how to solve it?

**Comment by PatriceJiang** [comment]
I thought about using okhttp and it is rejected for the lack of support for TLS 1.2. https://github.com/cocos2d/cocos2d-x/pull/19766. 

We may find a better lib to replacement HttpClient or simply upgrade it, and it will be decided soon.
