### ISSUE TITLE
UnboundLocalError: local variable 'gradle_support_ndk' referenced before assignment

### ISSUE THREAD

**Issue by TCTW** [cocos2d/cocos2d-x#20305]
- cocos2d-x version: 3.17.2
- devices test on: 
- developing environments
   - NDK version: android-ndk-r10e
   - Xcode version: 
   - VS version: 
   - browser type and version:

Steps to Reproduce:

1. 使用cocos new创建项目
2. 运行项目报错

liruipengdeMacBook-Pro:cocos2d-x-3.17.2 rex$ python setup.py 

Setting up cocos2d-x...
->Check environment variable COCOS_CONSOLE_ROOT
  ->Search for environment variable COCOS_CONSOLE_ROOT...
    ->COCOS_CONSOLE_ROOT is found : /Users/rex/Documents/software/cocos2d/cocos2d-x-3.17.2/tools/cocos2d-console/bin

->Check environment variable COCOS_X_ROOT
  ->Search for environment variable COCOS_X_ROOT...
    ->COCOS_X_ROOT is found : /Users/rex/Documents/software/cocos2d

->Check environment variable COCOS_TEMPLATES_ROOT
  ->Search for environment variable COCOS_TEMPLATES_ROOT...
    ->COCOS_TEMPLATES_ROOT is found : /Users/rex/Documents/software/cocos2d/cocos2d-x-3.17.2/templates

->Configuration for Android platform only, you can also skip and manually edit "/Users/rex/.bash_profile"

->Check environment variable NDK_ROOT
  ->Search for environment variable NDK_ROOT...
    ->NDK_ROOT is found : /Users/rex/Documents/ProgramFiles/ndk/android-ndk-r10e

->Check environment variable ANDROID_SDK_ROOT
  ->Search for environment variable ANDROID_SDK_ROOT...
    ->ANDROID_SDK_ROOT is found : /Users/rex/Library/Android/sdk

报错信息：

liruipengdeMacBook-Pro:HelloCocos rex$ cocos run -s ./ -p android --android-studio -m debug
Python 2.7.10
编译模式：debug
使用 Android Studio 工程：/Users/rex/Documents/Project/cocos2d-x/HelloCocos/proj.android
Traceback (most recent call last):
  File "/Users/rex/Documents/software/cocos2d/cocos2d-x-3.17.2/tools/cocos2d-console/bin/cocos.py", line 1081, in <module>
    run_plugin(command, argv, plugins)
  File "/Users/rex/Documents/software/cocos2d/cocos2d-x-3.17.2/tools/cocos2d-console/bin/cocos.py", line 967, in run_plugin
    dep_name, argv, plugins)
  File "/Users/rex/Documents/software/cocos2d/cocos2d-x-3.17.2/tools/cocos2d-console/bin/cocos.py", line 967, in run_plugin
    dep_name, argv, plugins)
  File "/Users/rex/Documents/software/cocos2d/cocos2d-x-3.17.2/tools/cocos2d-console/bin/cocos.py", line 970, in run_plugin
    plugin.run(argv, dependencies_objects)
  File "/Users/rex/Documents/software/cocos2d/cocos2d-x-3.17.2/tools/cocos2d-console/plugins/plugin_compile/project_compile.py", line 1530, in run
    self.build_android()
  File "/Users/rex/Documents/software/cocos2d/cocos2d-x-3.17.2/tools/cocos2d-console/plugins/plugin_compile/project_compile.py", line 478, in build_android
    self.app_abi, gradle_support_ndk)
UnboundLocalError: local variable 'gradle_support_ndk' referenced before assignment

**Comment by TCTW** [comment]
liruipengdeMacBook-Pro:HelloCocos rex$ cocos run -s ./ -p android -m debug --proj-dir ./proj.android-studio
Python 2.7.10
编译模式：debug
使用 Android Studio 工程：/Users/rex/Documents/Project/cocos2d-x/HelloCocos/./proj.android-studio
Traceback (most recent call last):
  File "/Users/rex/Documents/software/cocos2d/cocos2d-x-3.17.2/tools/cocos2d-console/bin/cocos.py", line 1081, in <module>
    run_plugin(command, argv, plugins)
  File "/Users/rex/Documents/software/cocos2d/cocos2d-x-3.17.2/tools/cocos2d-console/bin/cocos.py", line 967, in run_plugin
    dep_name, argv, plugins)
  File "/Users/rex/Documents/software/cocos2d/cocos2d-x-3.17.2/tools/cocos2d-console/bin/cocos.py", line 967, in run_plugin
    dep_name, argv, plugins)
  File "/Users/rex/Documents/software/cocos2d/cocos2d-x-3.17.2/tools/cocos2d-console/bin/cocos.py", line 970, in run_plugin
    plugin.run(argv, dependencies_objects)
  File "/Users/rex/Documents/software/cocos2d/cocos2d-x-3.17.2/tools/cocos2d-console/plugins/plugin_compile/project_compile.py", line 1530, in run
    self.build_android()
  File "/Users/rex/Documents/software/cocos2d/cocos2d-x-3.17.2/tools/cocos2d-console/plugins/plugin_compile/project_compile.py", line 478, in build_android
    self.app_abi, gradle_support_ndk)
UnboundLocalError: local variable 'gradle_support_ndk' referenced before assignment

**Comment by Peakchen** [comment]
how to resolve？

**Comment by gdoudeng** [comment]
+1

**Comment by qywangweiqang** [comment]
解决了吗
