### ISSUE TITLE
(SSL) I cannot download dependencies using download-deps.py (Windows)

### ISSUE THREAD

**Issue by JakubZ0** [cocos2d/cocos2d-x#20439]
- cocos2d-x version: newest one.
- devices test on: Windows.

Hi, the download-deps.py file doesn't seem to work, I have SSL problem - no idea why.

```
==> Prepare to download external libraries!
==> version file doesn't exist
==> Ready to download 'metal-support-22.zip' from 'https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/archive/metal-support-22.zip'
==> Download file retry 2
==> Ready to download 'metal-support-22.zip' from 'https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/archive/metal-support-22.zip'
==> Download file retry 3
==> Ready to download 'metal-support-22.zip' from 'https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/archive/metal-support-22.zip'
==> Download file retry 4
==> Ready to download 'metal-support-22.zip' from 'https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/archive/metal-support-22.zip'
==> Download file retry 5
==> Ready to download 'metal-support-22.zip' from 'https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/archive/metal-support-22.zip'
Traceback (most recent call last):
  File ".\download-deps.py", line 381, in <module>
    main()
  File ".\download-deps.py", line 376, in main
    installer.run(workpath, external_path, opts.remove_downloaded, opts.force_update, opts.download_only)
  File ".\download-deps.py", line 310, in run
    self.download_zip_file()
  File ".\download-deps.py", line 236, in download_zip_file
    self.download_file_with_retry(5, 3)
  File ".\download-deps.py", line 259, in download_file_with_retry
    raise err
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>

```

edit: adding 
```
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```
fixed script.

**Comment by mignaciolopez** [comment]
Hi @drawix where did u add those lines? same error on Mac

**Comment by JakubZ0** [comment]
> 
> 
> Hi @drawix where did u add those lines? same error on Mac

i believe in first lines, but i can't remember really.

**Comment by ForgetAll** [comment]
it works! thx! 👍🏻

**Comment by crookedbard** [comment]
import ssl
ssl._create_default_https_context = ssl._create_unverified_context 

in which file to add these lines?

If in download-deps.py then I get :

   ssl._create_default_https_context = ssl._create_unverified_context
AttributeError: 'module' object has no attribute '_create_unverified_context'

**Comment by crookedbard** [comment]
Adding these lines to the top of download-deps.py:

```
import ssl

# Create an SSL context with TLS support
ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS)
ssl_context.check_hostname = False
ssl_context.verify_mode = ssl.CERT_NONE
```

and updating python to 2.7.18
https://www.python.org/downloads/release/python-2718/?form=MG0AV3

solved the issue
