### ISSUE TITLE
URLError when python download-deps.py 

### ISSUE THREAD

**Issue by stray0652** [cocos2d/cocos2d-x#20666]
- cocos2d-x version: 4
- devices test on: macOS

1. $ git clone https://github.com/cocos2d/cocos2d-x.git

2. $ cd cocos2d-x
    cocos2d-x $ python download-deps.py

then

=======================================================
==> Prepare to download external libraries!
==> version file doesn't exist
==> Ready to download 'metal-support-22.zip' from 'https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/archive/metal-support-22.zip'
==> Download file retry 2
==> Ready to download 'metal-support-22.zip' from 'https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/archive/metal-support-22.zip'
==> Download file retry 3
==> Ready to download 'metal-support-22.zip' from 'https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/archive/metal-support-22.zip'
==> Download file retry 4
==> Ready to download 'metal-support-22.zip' from 'https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/archive/metal-support-22.zip'
==> Download file retry 5
==> Ready to download 'metal-support-22.zip' from 'https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/archive/metal-support-22.zip'
Traceback (most recent call last):
  File "download-deps.py", line 382, in <module>
    main()
  File "download-deps.py", line 377, in main
    installer.run(workpath, external_path, opts.remove_downloaded, opts.force_update, opts.download_only)
  File "download-deps.py", line 311, in run
    self.download_zip_file()
  File "download-deps.py", line 237, in download_zip_file
    self.download_file_with_retry(5, 3)
  File "download-deps.py", line 260, in download_file_with_retry
    raise err
URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>

**Comment by slackmoehrle** [comment]
The URL is valid: https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/archive/metal-support-22.zip

what python version are you using? Ensure that you are use 2.x please.

**Comment by stray0652** [comment]
@slackmoehrle 
thank you for comment.

I'm using python 2.7.10

$ python --version
Python 2.7.10

**Comment by slackmoehrle** [comment]
I've tried downloading every day using ./download-deps.py and I'm not having an issue. Are you having the issue still?

Feel free to use the URL I posted to grab the latest dependencies if it is still failing. I'm not sure why it would be for you to be honest.

**Comment by rh101** [comment]
This may be an OpenSSL issue not supporting the correct TLS version.

Try updating your OpenSSL.  You can follow the guide [here](https://comeroutewithme.com/2016/03/13/python-osx-openssl-issue/)

Otherwise, you can also disable the SSL check, but that isn't the recommended way to fix this issue. See [this](https://github.com/cocos2d/cocos2d-x/issues/20439).

**Comment by iusn** [comment]
same issue
I use python2.7
openssl version LibreSSL 2.8.3

**Comment by slackmoehrle** [comment]
I am not having an issue. Can you please post the output?

**Comment by rh101** [comment]
> I use python2.7

Check if it's the 32bit version of Python, and if not, try that instead.

**Comment by crookedbard** [comment]
same issue
