### ISSUE TITLE
Crash in cocos2dx game 3.17.2

### ISSUE THREAD

**Issue by ashK7** [cocos2d/cocos2d-x#20760]
- cocos2d-x version: 3.17.2
- devices test on android
- developing environments - Android - CMake
 
hello everyone if anyone knows how to sort out this crash kindly let me know.

Steps to Reproduce:

android.app.ApplicationPackageManager$2.onChecksumsReady
ApplicationPackageManager.java line 949
Fatal Exception: java.lang.AbstractMethodError: abstract method "void android.content.pm.PackageManager$OnChecksumsReadyListener.onChecksumsReady(java.util.List)"
       at android.app.ApplicationPackageManager$2.onChecksumsReady(ApplicationPackageManager.java:949)
       at android.content.pm.IOnChecksumsReadyListener$Stub.onTransact(IOnChecksumsReadyListener.java:87)
       at android.os.Binder.execTransactInternal(Binder.java:1184)
       at android.os.Binder.execTransact(Binder.java:1143)

**Comment by vigmu2gmes** [comment]
I have 3.17.2 set up on my computer. Are you able to compile the project to produce executable or apk?  Or is your game crashing while trying to open it on the source media that you are compiling?

**Comment by ashK7** [comment]
no brother it is a google play consol log details.
