### ISSUE TITLE
metal-support-22.zip failed to download dependencies

### ISSUE THREAD

**Issue by crookedbard** [cocos2d/cocos2d-x#20814]
C:\repos\cocos2d-x>python download-deps.py
The python version is 2.7.
=======================================================
==> Prepare to download external libraries!
==> version file doesn't exist
==> Ready to download 'metal-support-22.zip' from 'https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/archive/metal-support-22.zip'
==> Download file retry 2
==> Ready to download 'metal-support-22.zip' from 'https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/archive/metal-support-22.zip'
==> Download file retry 3
==> Ready to download 'metal-support-22.zip' from 'https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/archive/metal-support-22.zip'
==> Download file retry 4
==> Ready to download 'metal-support-22.zip' from 'https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/archive/metal-support-22.zip'
==> Download file retry 5
==> Ready to download 'metal-support-22.zip' from 'https://github.com/cocos2d/cocos2d-x-3rd-party-libs-bin/archive/metal-support-22.zip'
Traceback (most recent call last):
  File "download-deps.py", line 407, in <module>
    main()
  File "download-deps.py", line 400, in main
    opts.force_update, opts.download_only)
  File "download-deps.py", line 334, in run
    self.download_zip_file()
  File "download-deps.py", line 257, in download_zip_file
    self.download_file_with_retry(5, 3)
  File "download-deps.py", line 281, in download_file_with_retry
    raise err
AttributeError: 'URLError' object has no attribute 'code'

Steps to Reproduce:

1. python download-deps.py

**Comment by crookedbard** [comment]
Adding these lines to the top of download-deps.py:

import ssl

# Create an SSL context with TLS support
ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS)
ssl_context.check_hostname = False
ssl_context.verify_mode = ssl.CERT_NONE
and updating python to 2.7.18
https://www.python.org/downloads/release/python-2718/?form=MG0AV3

solved the issue
