### ISSUE TITLE
cocos2d-console throw exception when it does not have access to that directory

### ISSUE THREAD

**Issue by dabingnn** [cocos2d/cocos2d-x#9403]
Our developer report a minor bug in this thread
http://discuss.cocos2d-x.org/t/cocos2d-x-v3-3-rc2-released/18740/4

**Comment by minggo** [comment]
@natural-law 
This issue is fixed.
Could you please paste the PR for this issue?

**Comment by natural-law** [comment]
@minggo 
https://github.com/cocos2d/cocos2d-x/pull/9413
This is the PR solved the problem.

**Comment by claytoncurmi** [comment]
Hi,

I've just downloaded the latest version of Cocos2d-x from GitHub (project is stored in C:\Cocos2Dx folder). After running the download-deps.py and setup.py (and closing the terminal window), I tried to create a new project using the following command (I opened terminal in Administrator mode);

cocos.py new FooBar -p com.foo.bar-l cpp -d C:\FooBar

I'm getting the following response;

C:\Cocos2Dx\tools\cocos2d-console\bin>cocos.py new FooBar -p com.foo.bar -l cpp -d C:\FooBar
Running command: new
Traceback (most recent call last):
File "C:\Cocos2Dx\tools\cocos2d-console\bin\cocos.py", line 745, in 
run_plugin(command, argv, plugins)
File "C:\Cocos2Dx\tools\cocos2d-console\bin\cocos.py", line 708, in run_plugin
plugin.run(argv, dependencies_objects)
File "C:\Cocos2Dx\tools\cocos2d-console\plugins\project_new\project_new.py", line 216, in run
self.parse_args(argv)
File "C:\Cocos2Dx\tools\cocos2d-console\plugins\project_new\project_new.py", line 141, in parse_args
self.init(args)
File "C:\Cocos2Dx\tools\cocos2d-console\plugins\project_new\project_new.py", line 80, in init
self.templates = Templates(args.language, self.templates_paths, args.template)
File "C:\Cocos2Dx\tools\cocos2d-console\plugins\project_new\project_new.py", line 250, in __init
self._scan()
File "C:\Cocos2Dx\tools\cocos2d-console\plugins\project_new\project_new.py", line 269, in _scan
dirs = [name for name in os.listdir(templates_dir) if os.path.isdir(
WindowsError: [Error 5] Access is denied: 'C:\Users\Reaper\templates/.'

C:\Cocos2Dx\tools\cocos2d-console\bin>

**Comment by claytoncurmi** [comment]
Fixed, it was a problem in the paths (COCOS_X_ROOT was invalid)
