### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by claytoncurmi** [cocos2d/cocos2d-x#9528]
Hi,

I've just downloaded the latest version of Cocos2d-x from GitHub (project is stored in C:\Cocos2Dx folder). After running the download-deps.py and setup.py (and closing the terminal window), I tried to create a new project using the following command (I opened terminal in Administrator mode);

cocos.py new FooBar -p com.foo.bar-l cpp -d C:\FooBar

I'm getting the following response;

C:\Cocos2Dx\tools\cocos2d-console\bin>cocos.py new FooBar -p com.foo.bar -l cpp -d C:\FooBar
Running command: new
Traceback (most recent call last):
  File "C:\Cocos2Dx\tools\cocos2d-console\bin\cocos.py", line 745, in <module>
    run_plugin(command, argv, plugins)
  File "C:\Cocos2Dx\tools\cocos2d-console\bin\cocos.py", line 708, in run_plugin
    plugin.run(argv, dependencies_objects)
  File "C:\Cocos2Dx\tools\cocos2d-console\plugins\project_new\project_new.py", line 216, in run
    self.parse_args(argv)
  File "C:\Cocos2Dx\tools\cocos2d-console\plugins\project_new\project_new.py", line 141, in parse_args
    self.init(args)
  File "C:\Cocos2Dx\tools\cocos2d-console\plugins\project_new\project_new.py", line 80, in init
    self._templates = Templates(args.language, self._templates_paths, args.template)
  File "C:\Cocos2Dx\tools\cocos2d-console\plugins\project_new\project_new.py", line 250, in __init__
    self._scan()
  File "C:\Cocos2Dx\tools\cocos2d-console\plugins\project_new\project_new.py", line 269, in _scan
    dirs = [name for name in os.listdir(templates_dir) if os.path.isdir(
WindowsError: [Error 5] Access is denied: 'C:\Users\Reaper\templates/_._'

C:\Cocos2Dx\tools\cocos2d-console\bin>

**Comment by minggo** [comment]
@claytoncurmi
Could you please make sure you have the permission.

@natural-law modified the codes to catch the exception, but can not fix the permission issue because the exception is caused by your permission.

**Comment by natural-law** [comment]
It's duplicated with https://github.com/cocos2d/cocos2d-x/issues/9716
